replicaCount: 1

image:
  repository: rand-payment
  tag: develop
  pullPolicy: Always

service:
  type: ClusterIP
  port: 50061

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

migrations:
  skip: false
