// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/payment/v1/payment.proto

package paymentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_InitiateDeposit_FullMethodName       = "/payment.v1.PaymentService/InitiateDeposit"
	PaymentService_GetDepositStatus_FullMethodName      = "/payment.v1.PaymentService/GetDepositStatus"
	PaymentService_VerifyDepositStatus_FullMethodName   = "/payment.v1.PaymentService/VerifyDepositStatus"
	PaymentService_InitiateWithdrawal_FullMethodName    = "/payment.v1.PaymentService/InitiateWithdrawal"
	PaymentService_GetWithdrawalStatus_FullMethodName   = "/payment.v1.PaymentService/GetWithdrawalStatus"
	PaymentService_InitiateBankTransfer_FullMethodName  = "/payment.v1.PaymentService/InitiateBankTransfer"
	PaymentService_GetBankTransferStatus_FullMethodName = "/payment.v1.PaymentService/GetBankTransferStatus"
	PaymentService_VerifyWallet_FullMethodName          = "/payment.v1.PaymentService/VerifyWallet"
	PaymentService_VerifyBankAccount_FullMethodName     = "/payment.v1.PaymentService/VerifyBankAccount"
	PaymentService_VerifyIdentity_FullMethodName        = "/payment.v1.PaymentService/VerifyIdentity"
	PaymentService_GetTransaction_FullMethodName        = "/payment.v1.PaymentService/GetTransaction"
	PaymentService_ListTransactions_FullMethodName      = "/payment.v1.PaymentService/ListTransactions"
	PaymentService_CancelTransaction_FullMethodName     = "/payment.v1.PaymentService/CancelTransaction"
	PaymentService_ListProviders_FullMethodName         = "/payment.v1.PaymentService/ListProviders"
	PaymentService_GetProviderHealth_FullMethodName     = "/payment.v1.PaymentService/GetProviderHealth"
	PaymentService_ProcessWebhook_FullMethodName        = "/payment.v1.PaymentService/ProcessWebhook"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentService defines the payment service
type PaymentServiceClient interface {
	// Deposits: Mobile Money -> Stake Wallet
	InitiateDeposit(ctx context.Context, in *InitiateDepositRequest, opts ...grpc.CallOption) (*InitiateDepositResponse, error)
	GetDepositStatus(ctx context.Context, in *GetDepositStatusRequest, opts ...grpc.CallOption) (*GetDepositStatusResponse, error)
	VerifyDepositStatus(ctx context.Context, in *VerifyDepositStatusRequest, opts ...grpc.CallOption) (*VerifyDepositStatusResponse, error)
	// Withdrawals: Winning Wallet -> Mobile Money
	InitiateWithdrawal(ctx context.Context, in *InitiateWithdrawalRequest, opts ...grpc.CallOption) (*InitiateWithdrawalResponse, error)
	GetWithdrawalStatus(ctx context.Context, in *GetWithdrawalStatusRequest, opts ...grpc.CallOption) (*GetWithdrawalStatusResponse, error)
	// Bank Transfers
	InitiateBankTransfer(ctx context.Context, in *InitiateBankTransferRequest, opts ...grpc.CallOption) (*InitiateBankTransferResponse, error)
	GetBankTransferStatus(ctx context.Context, in *GetBankTransferStatusRequest, opts ...grpc.CallOption) (*GetBankTransferStatusResponse, error)
	// Verification (Enquiry)
	VerifyWallet(ctx context.Context, in *VerifyWalletRequest, opts ...grpc.CallOption) (*VerifyWalletResponse, error)
	VerifyBankAccount(ctx context.Context, in *VerifyBankAccountRequest, opts ...grpc.CallOption) (*VerifyBankAccountResponse, error)
	VerifyIdentity(ctx context.Context, in *VerifyIdentityRequest, opts ...grpc.CallOption) (*VerifyIdentityResponse, error)
	// Transaction Management
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	CancelTransaction(ctx context.Context, in *CancelTransactionRequest, opts ...grpc.CallOption) (*CancelTransactionResponse, error)
	// Provider Management
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	GetProviderHealth(ctx context.Context, in *GetProviderHealthRequest, opts ...grpc.CallOption) (*GetProviderHealthResponse, error)
	// Webhooks (for provider callbacks)
	ProcessWebhook(ctx context.Context, in *ProcessWebhookRequest, opts ...grpc.CallOption) (*ProcessWebhookResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) InitiateDeposit(ctx context.Context, in *InitiateDepositRequest, opts ...grpc.CallOption) (*InitiateDepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateDepositResponse)
	err := c.cc.Invoke(ctx, PaymentService_InitiateDeposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetDepositStatus(ctx context.Context, in *GetDepositStatusRequest, opts ...grpc.CallOption) (*GetDepositStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetDepositStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyDepositStatus(ctx context.Context, in *VerifyDepositStatusRequest, opts ...grpc.CallOption) (*VerifyDepositStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyDepositStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_VerifyDepositStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) InitiateWithdrawal(ctx context.Context, in *InitiateWithdrawalRequest, opts ...grpc.CallOption) (*InitiateWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateWithdrawalResponse)
	err := c.cc.Invoke(ctx, PaymentService_InitiateWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetWithdrawalStatus(ctx context.Context, in *GetWithdrawalStatusRequest, opts ...grpc.CallOption) (*GetWithdrawalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawalStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetWithdrawalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) InitiateBankTransfer(ctx context.Context, in *InitiateBankTransferRequest, opts ...grpc.CallOption) (*InitiateBankTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateBankTransferResponse)
	err := c.cc.Invoke(ctx, PaymentService_InitiateBankTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetBankTransferStatus(ctx context.Context, in *GetBankTransferStatusRequest, opts ...grpc.CallOption) (*GetBankTransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankTransferStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetBankTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyWallet(ctx context.Context, in *VerifyWalletRequest, opts ...grpc.CallOption) (*VerifyWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyWalletResponse)
	err := c.cc.Invoke(ctx, PaymentService_VerifyWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyBankAccount(ctx context.Context, in *VerifyBankAccountRequest, opts ...grpc.CallOption) (*VerifyBankAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyBankAccountResponse)
	err := c.cc.Invoke(ctx, PaymentService_VerifyBankAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyIdentity(ctx context.Context, in *VerifyIdentityRequest, opts ...grpc.CallOption) (*VerifyIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyIdentityResponse)
	err := c.cc.Invoke(ctx, PaymentService_VerifyIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CancelTransaction(ctx context.Context, in *CancelTransactionRequest, opts ...grpc.CallOption) (*CancelTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTransactionResponse)
	err := c.cc.Invoke(ctx, PaymentService_CancelTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetProviderHealth(ctx context.Context, in *GetProviderHealthRequest, opts ...grpc.CallOption) (*GetProviderHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderHealthResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetProviderHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ProcessWebhook(ctx context.Context, in *ProcessWebhookRequest, opts ...grpc.CallOption) (*ProcessWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessWebhookResponse)
	err := c.cc.Invoke(ctx, PaymentService_ProcessWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
//
// PaymentService defines the payment service
type PaymentServiceServer interface {
	// Deposits: Mobile Money -> Stake Wallet
	InitiateDeposit(context.Context, *InitiateDepositRequest) (*InitiateDepositResponse, error)
	GetDepositStatus(context.Context, *GetDepositStatusRequest) (*GetDepositStatusResponse, error)
	VerifyDepositStatus(context.Context, *VerifyDepositStatusRequest) (*VerifyDepositStatusResponse, error)
	// Withdrawals: Winning Wallet -> Mobile Money
	InitiateWithdrawal(context.Context, *InitiateWithdrawalRequest) (*InitiateWithdrawalResponse, error)
	GetWithdrawalStatus(context.Context, *GetWithdrawalStatusRequest) (*GetWithdrawalStatusResponse, error)
	// Bank Transfers
	InitiateBankTransfer(context.Context, *InitiateBankTransferRequest) (*InitiateBankTransferResponse, error)
	GetBankTransferStatus(context.Context, *GetBankTransferStatusRequest) (*GetBankTransferStatusResponse, error)
	// Verification (Enquiry)
	VerifyWallet(context.Context, *VerifyWalletRequest) (*VerifyWalletResponse, error)
	VerifyBankAccount(context.Context, *VerifyBankAccountRequest) (*VerifyBankAccountResponse, error)
	VerifyIdentity(context.Context, *VerifyIdentityRequest) (*VerifyIdentityResponse, error)
	// Transaction Management
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	CancelTransaction(context.Context, *CancelTransactionRequest) (*CancelTransactionResponse, error)
	// Provider Management
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	GetProviderHealth(context.Context, *GetProviderHealthRequest) (*GetProviderHealthResponse, error)
	// Webhooks (for provider callbacks)
	ProcessWebhook(context.Context, *ProcessWebhookRequest) (*ProcessWebhookResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) InitiateDeposit(context.Context, *InitiateDepositRequest) (*InitiateDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateDeposit not implemented")
}
func (UnimplementedPaymentServiceServer) GetDepositStatus(context.Context, *GetDepositStatusRequest) (*GetDepositStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositStatus not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyDepositStatus(context.Context, *VerifyDepositStatusRequest) (*VerifyDepositStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyDepositStatus not implemented")
}
func (UnimplementedPaymentServiceServer) InitiateWithdrawal(context.Context, *InitiateWithdrawalRequest) (*InitiateWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateWithdrawal not implemented")
}
func (UnimplementedPaymentServiceServer) GetWithdrawalStatus(context.Context, *GetWithdrawalStatusRequest) (*GetWithdrawalStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawalStatus not implemented")
}
func (UnimplementedPaymentServiceServer) InitiateBankTransfer(context.Context, *InitiateBankTransferRequest) (*InitiateBankTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateBankTransfer not implemented")
}
func (UnimplementedPaymentServiceServer) GetBankTransferStatus(context.Context, *GetBankTransferStatusRequest) (*GetBankTransferStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankTransferStatus not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyWallet(context.Context, *VerifyWalletRequest) (*VerifyWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyWallet not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyBankAccount(context.Context, *VerifyBankAccountRequest) (*VerifyBankAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBankAccount not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyIdentity(context.Context, *VerifyIdentityRequest) (*VerifyIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyIdentity not implemented")
}
func (UnimplementedPaymentServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedPaymentServiceServer) CancelTransaction(context.Context, *CancelTransactionRequest) (*CancelTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTransaction not implemented")
}
func (UnimplementedPaymentServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedPaymentServiceServer) GetProviderHealth(context.Context, *GetProviderHealthRequest) (*GetProviderHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderHealth not implemented")
}
func (UnimplementedPaymentServiceServer) ProcessWebhook(context.Context, *ProcessWebhookRequest) (*ProcessWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessWebhook not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_InitiateDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).InitiateDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_InitiateDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).InitiateDeposit(ctx, req.(*InitiateDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetDepositStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepositStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetDepositStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetDepositStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetDepositStatus(ctx, req.(*GetDepositStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyDepositStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyDepositStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyDepositStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_VerifyDepositStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyDepositStatus(ctx, req.(*VerifyDepositStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_InitiateWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).InitiateWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_InitiateWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).InitiateWithdrawal(ctx, req.(*InitiateWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetWithdrawalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetWithdrawalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetWithdrawalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetWithdrawalStatus(ctx, req.(*GetWithdrawalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_InitiateBankTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateBankTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).InitiateBankTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_InitiateBankTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).InitiateBankTransfer(ctx, req.(*InitiateBankTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetBankTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankTransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetBankTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetBankTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetBankTransferStatus(ctx, req.(*GetBankTransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_VerifyWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyWallet(ctx, req.(*VerifyWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_VerifyBankAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyBankAccount(ctx, req.(*VerifyBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_VerifyIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyIdentity(ctx, req.(*VerifyIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CancelTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CancelTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CancelTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CancelTransaction(ctx, req.(*CancelTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetProviderHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetProviderHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetProviderHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetProviderHealth(ctx, req.(*GetProviderHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ProcessWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ProcessWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ProcessWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ProcessWebhook(ctx, req.(*ProcessWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateDeposit",
			Handler:    _PaymentService_InitiateDeposit_Handler,
		},
		{
			MethodName: "GetDepositStatus",
			Handler:    _PaymentService_GetDepositStatus_Handler,
		},
		{
			MethodName: "VerifyDepositStatus",
			Handler:    _PaymentService_VerifyDepositStatus_Handler,
		},
		{
			MethodName: "InitiateWithdrawal",
			Handler:    _PaymentService_InitiateWithdrawal_Handler,
		},
		{
			MethodName: "GetWithdrawalStatus",
			Handler:    _PaymentService_GetWithdrawalStatus_Handler,
		},
		{
			MethodName: "InitiateBankTransfer",
			Handler:    _PaymentService_InitiateBankTransfer_Handler,
		},
		{
			MethodName: "GetBankTransferStatus",
			Handler:    _PaymentService_GetBankTransferStatus_Handler,
		},
		{
			MethodName: "VerifyWallet",
			Handler:    _PaymentService_VerifyWallet_Handler,
		},
		{
			MethodName: "VerifyBankAccount",
			Handler:    _PaymentService_VerifyBankAccount_Handler,
		},
		{
			MethodName: "VerifyIdentity",
			Handler:    _PaymentService_VerifyIdentity_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _PaymentService_GetTransaction_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _PaymentService_ListTransactions_Handler,
		},
		{
			MethodName: "CancelTransaction",
			Handler:    _PaymentService_CancelTransaction_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _PaymentService_ListProviders_Handler,
		},
		{
			MethodName: "GetProviderHealth",
			Handler:    _PaymentService_GetProviderHealth_Handler,
		},
		{
			MethodName: "ProcessWebhook",
			Handler:    _PaymentService_ProcessWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment/v1/payment.proto",
}
