// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/agent/management/v1/agent_management.proto

package agentmanagementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentManagementService_CreateAgent_FullMethodName                   = "/agent.management.v1.AgentManagementService/CreateAgent"
	AgentManagementService_GetAgent_FullMethodName                      = "/agent.management.v1.AgentManagementService/GetAgent"
	AgentManagementService_GetAgentByCode_FullMethodName                = "/agent.management.v1.AgentManagementService/GetAgentByCode"
	AgentManagementService_UpdateAgent_FullMethodName                   = "/agent.management.v1.AgentManagementService/UpdateAgent"
	AgentManagementService_ListAgents_FullMethodName                    = "/agent.management.v1.AgentManagementService/ListAgents"
	AgentManagementService_UpdateAgentStatus_FullMethodName             = "/agent.management.v1.AgentManagementService/UpdateAgentStatus"
	AgentManagementService_DeleteAgent_FullMethodName                   = "/agent.management.v1.AgentManagementService/DeleteAgent"
	AgentManagementService_CreateRetailer_FullMethodName                = "/agent.management.v1.AgentManagementService/CreateRetailer"
	AgentManagementService_GetRetailer_FullMethodName                   = "/agent.management.v1.AgentManagementService/GetRetailer"
	AgentManagementService_GetRetailerByCode_FullMethodName             = "/agent.management.v1.AgentManagementService/GetRetailerByCode"
	AgentManagementService_GetRetailerDetails_FullMethodName            = "/agent.management.v1.AgentManagementService/GetRetailerDetails"
	AgentManagementService_UpdateRetailer_FullMethodName                = "/agent.management.v1.AgentManagementService/UpdateRetailer"
	AgentManagementService_ListRetailers_FullMethodName                 = "/agent.management.v1.AgentManagementService/ListRetailers"
	AgentManagementService_UpdateRetailerStatus_FullMethodName          = "/agent.management.v1.AgentManagementService/UpdateRetailerStatus"
	AgentManagementService_DisableRetailer_FullMethodName               = "/agent.management.v1.AgentManagementService/DisableRetailer"
	AgentManagementService_EnableRetailer_FullMethodName                = "/agent.management.v1.AgentManagementService/EnableRetailer"
	AgentManagementService_AssignRetailerToAgent_FullMethodName         = "/agent.management.v1.AgentManagementService/AssignRetailerToAgent"
	AgentManagementService_ReassignRetailerToAgent_FullMethodName       = "/agent.management.v1.AgentManagementService/ReassignRetailerToAgent"
	AgentManagementService_UnassignRetailerFromAgent_FullMethodName     = "/agent.management.v1.AgentManagementService/UnassignRetailerFromAgent"
	AgentManagementService_GetAgentRetailers_FullMethodName             = "/agent.management.v1.AgentManagementService/GetAgentRetailers"
	AgentManagementService_GetRetailerAgent_FullMethodName              = "/agent.management.v1.AgentManagementService/GetRetailerAgent"
	AgentManagementService_CreatePOSDevice_FullMethodName               = "/agent.management.v1.AgentManagementService/CreatePOSDevice"
	AgentManagementService_GetPOSDevice_FullMethodName                  = "/agent.management.v1.AgentManagementService/GetPOSDevice"
	AgentManagementService_UpdatePOSDevice_FullMethodName               = "/agent.management.v1.AgentManagementService/UpdatePOSDevice"
	AgentManagementService_ListPOSDevices_FullMethodName                = "/agent.management.v1.AgentManagementService/ListPOSDevices"
	AgentManagementService_AssignPOSDeviceToRetailer_FullMethodName     = "/agent.management.v1.AgentManagementService/AssignPOSDeviceToRetailer"
	AgentManagementService_UnassignPOSDeviceFromRetailer_FullMethodName = "/agent.management.v1.AgentManagementService/UnassignPOSDeviceFromRetailer"
	AgentManagementService_CreateAgentKYC_FullMethodName                = "/agent.management.v1.AgentManagementService/CreateAgentKYC"
	AgentManagementService_UpdateAgentKYCStatus_FullMethodName          = "/agent.management.v1.AgentManagementService/UpdateAgentKYCStatus"
	AgentManagementService_CreateRetailerKYC_FullMethodName             = "/agent.management.v1.AgentManagementService/CreateRetailerKYC"
	AgentManagementService_UpdateRetailerKYCStatus_FullMethodName       = "/agent.management.v1.AgentManagementService/UpdateRetailerKYCStatus"
	AgentManagementService_GetRetailerCount_FullMethodName              = "/agent.management.v1.AgentManagementService/GetRetailerCount"
)

// AgentManagementServiceClient is the client API for AgentManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentManagementService provides management operations for agents, retailers, and related entities
type AgentManagementServiceClient interface {
	// Agent operations
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	GetAgentByCode(ctx context.Context, in *GetAgentByCodeRequest, opts ...grpc.CallOption) (*Agent, error)
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Retailer operations
	CreateRetailer(ctx context.Context, in *CreateRetailerRequest, opts ...grpc.CallOption) (*Retailer, error)
	GetRetailer(ctx context.Context, in *GetRetailerRequest, opts ...grpc.CallOption) (*Retailer, error)
	GetRetailerByCode(ctx context.Context, in *GetRetailerByCodeRequest, opts ...grpc.CallOption) (*Retailer, error)
	GetRetailerDetails(ctx context.Context, in *GetRetailerDetailsRequest, opts ...grpc.CallOption) (*RetailerDetailsResponse, error)
	UpdateRetailer(ctx context.Context, in *UpdateRetailerRequest, opts ...grpc.CallOption) (*Retailer, error)
	ListRetailers(ctx context.Context, in *ListRetailersRequest, opts ...grpc.CallOption) (*ListRetailersResponse, error)
	UpdateRetailerStatus(ctx context.Context, in *UpdateRetailerStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DisableRetailer(ctx context.Context, in *DisableRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	EnableRetailer(ctx context.Context, in *EnableRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Agent-Retailer relationship operations
	AssignRetailerToAgent(ctx context.Context, in *AssignRetailerToAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReassignRetailerToAgent(ctx context.Context, in *ReassignRetailerToAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnassignRetailerFromAgent(ctx context.Context, in *UnassignRetailerFromAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAgentRetailers(ctx context.Context, in *GetAgentRetailersRequest, opts ...grpc.CallOption) (*GetAgentRetailersResponse, error)
	GetRetailerAgent(ctx context.Context, in *GetRetailerAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// POS Device operations
	CreatePOSDevice(ctx context.Context, in *CreatePOSDeviceRequest, opts ...grpc.CallOption) (*POSDevice, error)
	GetPOSDevice(ctx context.Context, in *GetPOSDeviceRequest, opts ...grpc.CallOption) (*POSDevice, error)
	UpdatePOSDevice(ctx context.Context, in *UpdatePOSDeviceRequest, opts ...grpc.CallOption) (*POSDevice, error)
	ListPOSDevices(ctx context.Context, in *ListPOSDevicesRequest, opts ...grpc.CallOption) (*ListPOSDevicesResponse, error)
	AssignPOSDeviceToRetailer(ctx context.Context, in *AssignPOSDeviceToRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnassignPOSDeviceFromRetailer(ctx context.Context, in *UnassignPOSDeviceFromRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// KYC operations
	CreateAgentKYC(ctx context.Context, in *CreateAgentKYCRequest, opts ...grpc.CallOption) (*AgentKYC, error)
	UpdateAgentKYCStatus(ctx context.Context, in *UpdateAgentKYCStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateRetailerKYC(ctx context.Context, in *CreateRetailerKYCRequest, opts ...grpc.CallOption) (*RetailerKYC, error)
	UpdateRetailerKYCStatus(ctx context.Context, in *UpdateRetailerKYCStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Analytics operations
	GetRetailerCount(ctx context.Context, in *GetRetailerCountRequest, opts ...grpc.CallOption) (*GetRetailerCountResponse, error)
}

type agentManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentManagementServiceClient(cc grpc.ClientConnInterface) AgentManagementServiceClient {
	return &agentManagementServiceClient{cc}
}

func (c *agentManagementServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentManagementService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentManagementService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetAgentByCode(ctx context.Context, in *GetAgentByCodeRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentManagementService_GetAgentByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentManagementService_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentManagementService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UpdateAgentStatus(ctx context.Context, in *UpdateAgentStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_UpdateAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_DeleteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) CreateRetailer(ctx context.Context, in *CreateRetailerRequest, opts ...grpc.CallOption) (*Retailer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Retailer)
	err := c.cc.Invoke(ctx, AgentManagementService_CreateRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetRetailer(ctx context.Context, in *GetRetailerRequest, opts ...grpc.CallOption) (*Retailer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Retailer)
	err := c.cc.Invoke(ctx, AgentManagementService_GetRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetRetailerByCode(ctx context.Context, in *GetRetailerByCodeRequest, opts ...grpc.CallOption) (*Retailer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Retailer)
	err := c.cc.Invoke(ctx, AgentManagementService_GetRetailerByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetRetailerDetails(ctx context.Context, in *GetRetailerDetailsRequest, opts ...grpc.CallOption) (*RetailerDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetailerDetailsResponse)
	err := c.cc.Invoke(ctx, AgentManagementService_GetRetailerDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UpdateRetailer(ctx context.Context, in *UpdateRetailerRequest, opts ...grpc.CallOption) (*Retailer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Retailer)
	err := c.cc.Invoke(ctx, AgentManagementService_UpdateRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) ListRetailers(ctx context.Context, in *ListRetailersRequest, opts ...grpc.CallOption) (*ListRetailersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRetailersResponse)
	err := c.cc.Invoke(ctx, AgentManagementService_ListRetailers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UpdateRetailerStatus(ctx context.Context, in *UpdateRetailerStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_UpdateRetailerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) DisableRetailer(ctx context.Context, in *DisableRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_DisableRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) EnableRetailer(ctx context.Context, in *EnableRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_EnableRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) AssignRetailerToAgent(ctx context.Context, in *AssignRetailerToAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_AssignRetailerToAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) ReassignRetailerToAgent(ctx context.Context, in *ReassignRetailerToAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_ReassignRetailerToAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UnassignRetailerFromAgent(ctx context.Context, in *UnassignRetailerFromAgentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_UnassignRetailerFromAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetAgentRetailers(ctx context.Context, in *GetAgentRetailersRequest, opts ...grpc.CallOption) (*GetAgentRetailersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentRetailersResponse)
	err := c.cc.Invoke(ctx, AgentManagementService_GetAgentRetailers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetRetailerAgent(ctx context.Context, in *GetRetailerAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, AgentManagementService_GetRetailerAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) CreatePOSDevice(ctx context.Context, in *CreatePOSDeviceRequest, opts ...grpc.CallOption) (*POSDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(POSDevice)
	err := c.cc.Invoke(ctx, AgentManagementService_CreatePOSDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetPOSDevice(ctx context.Context, in *GetPOSDeviceRequest, opts ...grpc.CallOption) (*POSDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(POSDevice)
	err := c.cc.Invoke(ctx, AgentManagementService_GetPOSDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UpdatePOSDevice(ctx context.Context, in *UpdatePOSDeviceRequest, opts ...grpc.CallOption) (*POSDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(POSDevice)
	err := c.cc.Invoke(ctx, AgentManagementService_UpdatePOSDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) ListPOSDevices(ctx context.Context, in *ListPOSDevicesRequest, opts ...grpc.CallOption) (*ListPOSDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPOSDevicesResponse)
	err := c.cc.Invoke(ctx, AgentManagementService_ListPOSDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) AssignPOSDeviceToRetailer(ctx context.Context, in *AssignPOSDeviceToRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_AssignPOSDeviceToRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UnassignPOSDeviceFromRetailer(ctx context.Context, in *UnassignPOSDeviceFromRetailerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_UnassignPOSDeviceFromRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) CreateAgentKYC(ctx context.Context, in *CreateAgentKYCRequest, opts ...grpc.CallOption) (*AgentKYC, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentKYC)
	err := c.cc.Invoke(ctx, AgentManagementService_CreateAgentKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UpdateAgentKYCStatus(ctx context.Context, in *UpdateAgentKYCStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_UpdateAgentKYCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) CreateRetailerKYC(ctx context.Context, in *CreateRetailerKYCRequest, opts ...grpc.CallOption) (*RetailerKYC, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetailerKYC)
	err := c.cc.Invoke(ctx, AgentManagementService_CreateRetailerKYC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) UpdateRetailerKYCStatus(ctx context.Context, in *UpdateRetailerKYCStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentManagementService_UpdateRetailerKYCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentManagementServiceClient) GetRetailerCount(ctx context.Context, in *GetRetailerCountRequest, opts ...grpc.CallOption) (*GetRetailerCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRetailerCountResponse)
	err := c.cc.Invoke(ctx, AgentManagementService_GetRetailerCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentManagementServiceServer is the server API for AgentManagementService service.
// All implementations must embed UnimplementedAgentManagementServiceServer
// for forward compatibility.
//
// AgentManagementService provides management operations for agents, retailers, and related entities
type AgentManagementServiceServer interface {
	// Agent operations
	CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error)
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	GetAgentByCode(context.Context, *GetAgentByCodeRequest) (*Agent, error)
	UpdateAgent(context.Context, *UpdateAgentRequest) (*Agent, error)
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*emptypb.Empty, error)
	DeleteAgent(context.Context, *DeleteAgentRequest) (*emptypb.Empty, error)
	// Retailer operations
	CreateRetailer(context.Context, *CreateRetailerRequest) (*Retailer, error)
	GetRetailer(context.Context, *GetRetailerRequest) (*Retailer, error)
	GetRetailerByCode(context.Context, *GetRetailerByCodeRequest) (*Retailer, error)
	GetRetailerDetails(context.Context, *GetRetailerDetailsRequest) (*RetailerDetailsResponse, error)
	UpdateRetailer(context.Context, *UpdateRetailerRequest) (*Retailer, error)
	ListRetailers(context.Context, *ListRetailersRequest) (*ListRetailersResponse, error)
	UpdateRetailerStatus(context.Context, *UpdateRetailerStatusRequest) (*emptypb.Empty, error)
	DisableRetailer(context.Context, *DisableRetailerRequest) (*emptypb.Empty, error)
	EnableRetailer(context.Context, *EnableRetailerRequest) (*emptypb.Empty, error)
	// Agent-Retailer relationship operations
	AssignRetailerToAgent(context.Context, *AssignRetailerToAgentRequest) (*emptypb.Empty, error)
	ReassignRetailerToAgent(context.Context, *ReassignRetailerToAgentRequest) (*emptypb.Empty, error)
	UnassignRetailerFromAgent(context.Context, *UnassignRetailerFromAgentRequest) (*emptypb.Empty, error)
	GetAgentRetailers(context.Context, *GetAgentRetailersRequest) (*GetAgentRetailersResponse, error)
	GetRetailerAgent(context.Context, *GetRetailerAgentRequest) (*Agent, error)
	// POS Device operations
	CreatePOSDevice(context.Context, *CreatePOSDeviceRequest) (*POSDevice, error)
	GetPOSDevice(context.Context, *GetPOSDeviceRequest) (*POSDevice, error)
	UpdatePOSDevice(context.Context, *UpdatePOSDeviceRequest) (*POSDevice, error)
	ListPOSDevices(context.Context, *ListPOSDevicesRequest) (*ListPOSDevicesResponse, error)
	AssignPOSDeviceToRetailer(context.Context, *AssignPOSDeviceToRetailerRequest) (*emptypb.Empty, error)
	UnassignPOSDeviceFromRetailer(context.Context, *UnassignPOSDeviceFromRetailerRequest) (*emptypb.Empty, error)
	// KYC operations
	CreateAgentKYC(context.Context, *CreateAgentKYCRequest) (*AgentKYC, error)
	UpdateAgentKYCStatus(context.Context, *UpdateAgentKYCStatusRequest) (*emptypb.Empty, error)
	CreateRetailerKYC(context.Context, *CreateRetailerKYCRequest) (*RetailerKYC, error)
	UpdateRetailerKYCStatus(context.Context, *UpdateRetailerKYCStatusRequest) (*emptypb.Empty, error)
	// Analytics operations
	GetRetailerCount(context.Context, *GetRetailerCountRequest) (*GetRetailerCountResponse, error)
	mustEmbedUnimplementedAgentManagementServiceServer()
}

// UnimplementedAgentManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentManagementServiceServer struct{}

func (UnimplementedAgentManagementServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetAgent(context.Context, *GetAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetAgentByCode(context.Context, *GetAgentByCodeRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentByCode not implemented")
}
func (UnimplementedAgentManagementServiceServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentManagementServiceServer) UpdateAgentStatus(context.Context, *UpdateAgentStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentStatus not implemented")
}
func (UnimplementedAgentManagementServiceServer) DeleteAgent(context.Context, *DeleteAgentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) CreateRetailer(context.Context, *CreateRetailerRequest) (*Retailer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRetailer not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetRetailer(context.Context, *GetRetailerRequest) (*Retailer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailer not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetRetailerByCode(context.Context, *GetRetailerByCodeRequest) (*Retailer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailerByCode not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetRetailerDetails(context.Context, *GetRetailerDetailsRequest) (*RetailerDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailerDetails not implemented")
}
func (UnimplementedAgentManagementServiceServer) UpdateRetailer(context.Context, *UpdateRetailerRequest) (*Retailer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRetailer not implemented")
}
func (UnimplementedAgentManagementServiceServer) ListRetailers(context.Context, *ListRetailersRequest) (*ListRetailersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRetailers not implemented")
}
func (UnimplementedAgentManagementServiceServer) UpdateRetailerStatus(context.Context, *UpdateRetailerStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRetailerStatus not implemented")
}
func (UnimplementedAgentManagementServiceServer) DisableRetailer(context.Context, *DisableRetailerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableRetailer not implemented")
}
func (UnimplementedAgentManagementServiceServer) EnableRetailer(context.Context, *EnableRetailerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableRetailer not implemented")
}
func (UnimplementedAgentManagementServiceServer) AssignRetailerToAgent(context.Context, *AssignRetailerToAgentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignRetailerToAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) ReassignRetailerToAgent(context.Context, *ReassignRetailerToAgentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReassignRetailerToAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) UnassignRetailerFromAgent(context.Context, *UnassignRetailerFromAgentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignRetailerFromAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetAgentRetailers(context.Context, *GetAgentRetailersRequest) (*GetAgentRetailersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentRetailers not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetRetailerAgent(context.Context, *GetRetailerAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailerAgent not implemented")
}
func (UnimplementedAgentManagementServiceServer) CreatePOSDevice(context.Context, *CreatePOSDeviceRequest) (*POSDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePOSDevice not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetPOSDevice(context.Context, *GetPOSDeviceRequest) (*POSDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPOSDevice not implemented")
}
func (UnimplementedAgentManagementServiceServer) UpdatePOSDevice(context.Context, *UpdatePOSDeviceRequest) (*POSDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePOSDevice not implemented")
}
func (UnimplementedAgentManagementServiceServer) ListPOSDevices(context.Context, *ListPOSDevicesRequest) (*ListPOSDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPOSDevices not implemented")
}
func (UnimplementedAgentManagementServiceServer) AssignPOSDeviceToRetailer(context.Context, *AssignPOSDeviceToRetailerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignPOSDeviceToRetailer not implemented")
}
func (UnimplementedAgentManagementServiceServer) UnassignPOSDeviceFromRetailer(context.Context, *UnassignPOSDeviceFromRetailerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignPOSDeviceFromRetailer not implemented")
}
func (UnimplementedAgentManagementServiceServer) CreateAgentKYC(context.Context, *CreateAgentKYCRequest) (*AgentKYC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgentKYC not implemented")
}
func (UnimplementedAgentManagementServiceServer) UpdateAgentKYCStatus(context.Context, *UpdateAgentKYCStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentKYCStatus not implemented")
}
func (UnimplementedAgentManagementServiceServer) CreateRetailerKYC(context.Context, *CreateRetailerKYCRequest) (*RetailerKYC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRetailerKYC not implemented")
}
func (UnimplementedAgentManagementServiceServer) UpdateRetailerKYCStatus(context.Context, *UpdateRetailerKYCStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRetailerKYCStatus not implemented")
}
func (UnimplementedAgentManagementServiceServer) GetRetailerCount(context.Context, *GetRetailerCountRequest) (*GetRetailerCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRetailerCount not implemented")
}
func (UnimplementedAgentManagementServiceServer) mustEmbedUnimplementedAgentManagementServiceServer() {
}
func (UnimplementedAgentManagementServiceServer) testEmbeddedByValue() {}

// UnsafeAgentManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentManagementServiceServer will
// result in compilation errors.
type UnsafeAgentManagementServiceServer interface {
	mustEmbedUnimplementedAgentManagementServiceServer()
}

func RegisterAgentManagementServiceServer(s grpc.ServiceRegistrar, srv AgentManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentManagementService_ServiceDesc, srv)
}

func _AgentManagementService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetAgentByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetAgentByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetAgentByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetAgentByCode(ctx, req.(*GetAgentByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UpdateAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UpdateAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UpdateAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UpdateAgentStatus(ctx, req.(*UpdateAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_DeleteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_CreateRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).CreateRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_CreateRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).CreateRetailer(ctx, req.(*CreateRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetRetailer(ctx, req.(*GetRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetRetailerByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetailerByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetRetailerByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetRetailerByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetRetailerByCode(ctx, req.(*GetRetailerByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetRetailerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetailerDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetRetailerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetRetailerDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetRetailerDetails(ctx, req.(*GetRetailerDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UpdateRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UpdateRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UpdateRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UpdateRetailer(ctx, req.(*UpdateRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_ListRetailers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRetailersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).ListRetailers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_ListRetailers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).ListRetailers(ctx, req.(*ListRetailersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UpdateRetailerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRetailerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UpdateRetailerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UpdateRetailerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UpdateRetailerStatus(ctx, req.(*UpdateRetailerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_DisableRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).DisableRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_DisableRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).DisableRetailer(ctx, req.(*DisableRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_EnableRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).EnableRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_EnableRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).EnableRetailer(ctx, req.(*EnableRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_AssignRetailerToAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRetailerToAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).AssignRetailerToAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_AssignRetailerToAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).AssignRetailerToAgent(ctx, req.(*AssignRetailerToAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_ReassignRetailerToAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignRetailerToAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).ReassignRetailerToAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_ReassignRetailerToAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).ReassignRetailerToAgent(ctx, req.(*ReassignRetailerToAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UnassignRetailerFromAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignRetailerFromAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UnassignRetailerFromAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UnassignRetailerFromAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UnassignRetailerFromAgent(ctx, req.(*UnassignRetailerFromAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetAgentRetailers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRetailersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetAgentRetailers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetAgentRetailers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetAgentRetailers(ctx, req.(*GetAgentRetailersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetRetailerAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetailerAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetRetailerAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetRetailerAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetRetailerAgent(ctx, req.(*GetRetailerAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_CreatePOSDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePOSDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).CreatePOSDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_CreatePOSDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).CreatePOSDevice(ctx, req.(*CreatePOSDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetPOSDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPOSDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetPOSDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetPOSDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetPOSDevice(ctx, req.(*GetPOSDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UpdatePOSDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePOSDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UpdatePOSDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UpdatePOSDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UpdatePOSDevice(ctx, req.(*UpdatePOSDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_ListPOSDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPOSDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).ListPOSDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_ListPOSDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).ListPOSDevices(ctx, req.(*ListPOSDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_AssignPOSDeviceToRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignPOSDeviceToRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).AssignPOSDeviceToRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_AssignPOSDeviceToRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).AssignPOSDeviceToRetailer(ctx, req.(*AssignPOSDeviceToRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UnassignPOSDeviceFromRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignPOSDeviceFromRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UnassignPOSDeviceFromRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UnassignPOSDeviceFromRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UnassignPOSDeviceFromRetailer(ctx, req.(*UnassignPOSDeviceFromRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_CreateAgentKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).CreateAgentKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_CreateAgentKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).CreateAgentKYC(ctx, req.(*CreateAgentKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UpdateAgentKYCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentKYCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UpdateAgentKYCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UpdateAgentKYCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UpdateAgentKYCStatus(ctx, req.(*UpdateAgentKYCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_CreateRetailerKYC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRetailerKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).CreateRetailerKYC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_CreateRetailerKYC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).CreateRetailerKYC(ctx, req.(*CreateRetailerKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_UpdateRetailerKYCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRetailerKYCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).UpdateRetailerKYCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_UpdateRetailerKYCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).UpdateRetailerKYCStatus(ctx, req.(*UpdateRetailerKYCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentManagementService_GetRetailerCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRetailerCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentManagementServiceServer).GetRetailerCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentManagementService_GetRetailerCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentManagementServiceServer).GetRetailerCount(ctx, req.(*GetRetailerCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentManagementService_ServiceDesc is the grpc.ServiceDesc for AgentManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.management.v1.AgentManagementService",
	HandlerType: (*AgentManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentManagementService_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentManagementService_GetAgent_Handler,
		},
		{
			MethodName: "GetAgentByCode",
			Handler:    _AgentManagementService_GetAgentByCode_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentManagementService_UpdateAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentManagementService_ListAgents_Handler,
		},
		{
			MethodName: "UpdateAgentStatus",
			Handler:    _AgentManagementService_UpdateAgentStatus_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _AgentManagementService_DeleteAgent_Handler,
		},
		{
			MethodName: "CreateRetailer",
			Handler:    _AgentManagementService_CreateRetailer_Handler,
		},
		{
			MethodName: "GetRetailer",
			Handler:    _AgentManagementService_GetRetailer_Handler,
		},
		{
			MethodName: "GetRetailerByCode",
			Handler:    _AgentManagementService_GetRetailerByCode_Handler,
		},
		{
			MethodName: "GetRetailerDetails",
			Handler:    _AgentManagementService_GetRetailerDetails_Handler,
		},
		{
			MethodName: "UpdateRetailer",
			Handler:    _AgentManagementService_UpdateRetailer_Handler,
		},
		{
			MethodName: "ListRetailers",
			Handler:    _AgentManagementService_ListRetailers_Handler,
		},
		{
			MethodName: "UpdateRetailerStatus",
			Handler:    _AgentManagementService_UpdateRetailerStatus_Handler,
		},
		{
			MethodName: "DisableRetailer",
			Handler:    _AgentManagementService_DisableRetailer_Handler,
		},
		{
			MethodName: "EnableRetailer",
			Handler:    _AgentManagementService_EnableRetailer_Handler,
		},
		{
			MethodName: "AssignRetailerToAgent",
			Handler:    _AgentManagementService_AssignRetailerToAgent_Handler,
		},
		{
			MethodName: "ReassignRetailerToAgent",
			Handler:    _AgentManagementService_ReassignRetailerToAgent_Handler,
		},
		{
			MethodName: "UnassignRetailerFromAgent",
			Handler:    _AgentManagementService_UnassignRetailerFromAgent_Handler,
		},
		{
			MethodName: "GetAgentRetailers",
			Handler:    _AgentManagementService_GetAgentRetailers_Handler,
		},
		{
			MethodName: "GetRetailerAgent",
			Handler:    _AgentManagementService_GetRetailerAgent_Handler,
		},
		{
			MethodName: "CreatePOSDevice",
			Handler:    _AgentManagementService_CreatePOSDevice_Handler,
		},
		{
			MethodName: "GetPOSDevice",
			Handler:    _AgentManagementService_GetPOSDevice_Handler,
		},
		{
			MethodName: "UpdatePOSDevice",
			Handler:    _AgentManagementService_UpdatePOSDevice_Handler,
		},
		{
			MethodName: "ListPOSDevices",
			Handler:    _AgentManagementService_ListPOSDevices_Handler,
		},
		{
			MethodName: "AssignPOSDeviceToRetailer",
			Handler:    _AgentManagementService_AssignPOSDeviceToRetailer_Handler,
		},
		{
			MethodName: "UnassignPOSDeviceFromRetailer",
			Handler:    _AgentManagementService_UnassignPOSDeviceFromRetailer_Handler,
		},
		{
			MethodName: "CreateAgentKYC",
			Handler:    _AgentManagementService_CreateAgentKYC_Handler,
		},
		{
			MethodName: "UpdateAgentKYCStatus",
			Handler:    _AgentManagementService_UpdateAgentKYCStatus_Handler,
		},
		{
			MethodName: "CreateRetailerKYC",
			Handler:    _AgentManagementService_CreateRetailerKYC_Handler,
		},
		{
			MethodName: "UpdateRetailerKYCStatus",
			Handler:    _AgentManagementService_UpdateRetailerKYCStatus_Handler,
		},
		{
			MethodName: "GetRetailerCount",
			Handler:    _AgentManagementService_GetRetailerCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/management/v1/agent_management.proto",
}
