apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-ticket-staging
  namespace: argocd
  labels:
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: service-ticket=ghcr.io/nexalabshq/rand-ticket:staging
    argocd-image-updater.argoproj.io/service-ticket.update-strategy: latest
    argocd-image-updater.argoproj.io/service-ticket.allow-tags: regexp:^staging-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/service-ticket.helm.image-name: service-ticket.image.repository
    argocd-image-updater.argoproj.io/service-ticket.helm.image-tag: service-ticket.image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-staging
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  source:
    repoURL: https://github.com/nexalabshq/rand-microservices
    targetRevision: staging
    path: helm/microservices
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        - name: service-admin-management.enabled
          value: "false"
        - name: service-agent-auth.enabled
          value: "false"
        - name: service-agent-management.enabled
          value: "false"
        - name: service-api-gateway.enabled
          value: "false"
        - name: service-draw.enabled
          value: "false"
        - name: service-game.enabled
          value: "false"
        - name: service-payment.enabled
          value: "false"
        - name: service-terminal.enabled
          value: "false"
        - name: service-ticket.enabled
          value: "true"
        - name: service-wallet.enabled
          value: "false"
      values: |
        global:
          imagePullSecrets:
            - name: ghcr-secret
