apiVersion: v1
data:
  DATABASE_CONN_MAX_IDLE_TIME: 600s
  DATABASE_CONN_MAX_LIFETIME: 1800s
  DATABASE_HOST: postgres-payment.external-services.svc.cluster.local
  DATABASE_MAX_IDLE_CONNS: "10"
  DATABASE_MAX_OPEN_CONNS: "25"
  DATABASE_NAME: payment_service
  DATABASE_PORT: "5432"
  DATABASE_SSL_MODE: disable
  DATABASE_USER: payment
  ENVIRONMENT: dev
  JAEGER_ENDPOINT: http://jaeger-dev.observability.svc.cluster.local:4318
  KAFKA_BROKERS: kafka.external-services.svc.cluster.local:9092
  KAFKA_CONSUMER_GROUP: payment-service-group
  KAFKA_ENABLED: "true"
  KAFKA_TOPIC: payment-events
  KAFKA_TOPIC_PREFIX: randco
  LOGGING_FORMAT: json
  LOGGING_LEVEL: info
  PROVIDERS_ORANGE_BASE_URL: https://fblapp.test.fidelitybank.com.gh:1065/OrangeEx/
  PROVIDERS_ORANGE_CALLBACK_URL: https://api.dev.randlottery.com/api/v1/webhooks/orange
  PROVIDERS_ORANGE_ENABLED: "true"
  PROVIDERS_ORANGE_ENVIRONMENT: UAT
  PROVIDERS_ORANGE_MAX_RETRY: "3"
  PROVIDERS_ORANGE_RETRY_DELAY_SECONDS: 2s
  PROVIDERS_ORANGE_TIMEOUT_SECONDS: 30s
  REDIS_DB: "0"
  REDIS_HOST: redis-payment.external-services.svc.cluster.local
  REDIS_PORT: "6387"
  SERVER_MODE: dev
  SERVER_PORT: "50061"
  SERVICE_NAME: service-payment
  SERVICES_WALLET_HOST: service-wallet-dev
  SERVICES_WALLET_PORT: "50059"
  TRACING_ENABLED: "true"
  TRACING_ENVIRONMENT: dev
  TRACING_JAEGER_ENDPOINT: http://jaeger-dev.observability.svc.cluster.local:4318
  TRACING_SAMPLE_RATE: "1.0"
  TRACING_SERVICE_NAME: payment-service
  TRACING_SERVICE_VERSION: 1.0.0
kind: ConfigMap
metadata:
  name: service-payment-dev-config
  namespace: microservices-dev
  labels:
    app.kubernetes.io/instance: service-payment-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service-payment
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-payment-1.0.0
