apiVersion: v1
data:
  DATABASE_PASSWORD: UGF5bWVudDIwMjVTZWN1cmU=
  DATABASE_URL: cG9zdGdyZXNxbDovL3BheW1lbnQ6UGF5bWVudDIwMjVTZWN1cmVAcG9zdGdyZXMtcGF5bWVudC5leHRlcm5hbC1zZXJ2aWNlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3BheW1lbnRfc2VydmljZT9zc2xtb2RlPWRpc2FibGU=
  JWT_SECRET: cmFuZGxvdHRlcnlsdGQtand0LXNlY3JldC1oOGY5eDJ3MXY3cTVrM205bjZiNGM4ZDJlNWY3ZzBqMQ==
  PAYMENT_DATABASE_URL: cG9zdGdyZXNxbDovL3BheW1lbnQ6UGF5bWVudDIwMjVTZWN1cmVAcG9zdGdyZXMtcGF5bWVudC5leHRlcm5hbC1zZXJ2aWNlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3BheW1lbnRfc2VydmljZT9zc2xtb2RlPWRpc2FibGU=
  PAYMENT_WEBHOOK_SECRET: ""
  PROVIDERS_AIRTELTIGO_CLIENT_ID: ""
  PROVIDERS_AIRTELTIGO_CLIENT_SECRET: ""
  PROVIDERS_MTN_API_KEY: ""
  PROVIDERS_MTN_API_SECRET: ""
  PROVIDERS_MTN_SECRET_KEY: M2QyNjE1ZDQtYmIxYS00MmIzLTk4MTQtZDg0NmIxOTg4MTg3
  PROVIDERS_MTN_SECRET_TOKEN: NzY1YWVlN2QtNTk1Ny00Mzc1LWFhYjYtMzYyNDc2ZTVmZGNl
  PROVIDERS_MTN_SUBSCRIPTION_KEY: ""
  PROVIDERS_ORANGE_CALLBACK_SECRET: MmRiMmFhNWU4Y2VhY2VmZTczNTYwZTc2ZjY2NGUwY2Q2NGYzMjQ0OTQ0ZGVkNWZiMjRhOTM5ZDNiYWI2MjMzYg==
  PROVIDERS_ORANGE_SECRET_KEY: YTE2MWEyYjMtNGY2NS00ZDg2LTg3ZjYtNjYzYTFlYzRhNjEy
  PROVIDERS_ORANGE_SECRET_TOKEN: NzllYWFkZGQtNTc2Ny00YWZkLThiOTQtNjc4ZjM4MmFmZDVl
  PROVIDERS_TELECEL_CLIENT_ID: ""
  PROVIDERS_TELECEL_CLIENT_SECRET: ""
  PROVIDERS_TELECEL_SECRET_KEY: M2QyNjE1ZDQtYmIxYS00MmIzLTk4MTQtZDg0NmIxOTg4MTg3
  PROVIDERS_TELECEL_SECRET_TOKEN: NzY1YWVlN2QtNTk1Ny00Mzc1LWFhYjYtMzYyNDc2ZTVmZGNl
  REDIS_PASSWORD: N3UxUG5Oa1B0d3dDcmtKOGQxQ3lLUElVdWFMUEg1UFE=
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1wYXltZW50LmV4dGVybmFsLXNlcnZpY2VzLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkvMA==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"service-payment-dev","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"service-payment","app.kubernetes.io/version":"1.0.0","helm.sh/chart":"service-payment-1.0.0"},"name":"service-payment-dev-secret","namespace":"microservices-dev"},"stringData":{"DATABASE_PASSWORD":"Payment2025Secure","DATABASE_URL":"postgresql://payment:Payment2025Secure@postgres-payment.external-services.svc.cluster.local:5432/payment_service?sslmode=disable","JWT_SECRET":"randlotteryltd-jwt-secret-h8f9x2w1v7q5k3m9n6b4c8d2e5f7g0j1","PROVIDERS_ORANGE_SECRET_KEY":"a161a2b3-4f65-4d86-87f6-663a1ec4a612","PROVIDERS_ORANGE_SECRET_TOKEN":"79eaaddd-5767-4afd-8b94-678f382afd5e","REDIS_PASSWORD":"7u1PnNkPtwwCrkJ8d1CyKPIUuaLPH5PQ"},"type":"Opaque"}
  creationTimestamp: "2025-10-08T21:35:07Z"
  labels:
    app.kubernetes.io/instance: service-payment-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service-payment
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-payment-1.0.0
  name: service-payment-dev-secret
  namespace: microservices-dev
  resourceVersion: "63411787"
  uid: 3c138e95-735d-4b70-ad96-5d1807d8694e
type: Opaque
