apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-web-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: admin-web=ghcr.io/nexalabshq/rand-admin-web:staging
    argocd-image-updater.argoproj.io/admin-web.update-strategy: latest
    argocd-image-updater.argoproj.io/admin-web.allow-tags: regexp:^staging-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/admin-web.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/admin-web.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nexalabshq/rand-admin-web
    targetRevision: staging
    path: helm/admin-web
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: staging  # This will use the latest staging tag
  destination:
    server: https://kubernetes.default.svc
    namespace: randlottery-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10