apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-dev
  namespace: argocd
  labels:
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  project: default
  source:
    repoURL: https://github.com/nexalabshq/rand-microservices
    targetRevision: develop
    path: helm/jaeger
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
