// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/ticket_service.proto

package ticketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BetLine represents a single bet line on a ticket
type BetLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    int32                  `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	BetType       string                 `protobuf:"bytes,2,opt,name=bet_type,json=betType,proto3" json:"bet_type,omitempty"`
	Numbers       []int32                `protobuf:"varint,3,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Banker        []int32                `protobuf:"varint,4,rep,packed,name=banker,proto3" json:"banker,omitempty"`
	Opposed       []int32                `protobuf:"varint,5,rep,packed,name=opposed,proto3" json:"opposed,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetLine) Reset() {
	*x = BetLine{}
	mi := &file_proto_ticket_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetLine) ProtoMessage() {}

func (x *BetLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetLine.ProtoReflect.Descriptor instead.
func (*BetLine) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{0}
}

func (x *BetLine) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *BetLine) GetBetType() string {
	if x != nil {
		return x.BetType
	}
	return ""
}

func (x *BetLine) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *BetLine) GetBanker() []int32 {
	if x != nil {
		return x.Banker
	}
	return nil
}

func (x *BetLine) GetOpposed() []int32 {
	if x != nil {
		return x.Opposed
	}
	return nil
}

func (x *BetLine) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// SecurityFeatures contains ticket security information
type SecurityFeatures struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QrCode           string                 `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	Barcode          string                 `protobuf:"bytes,2,opt,name=barcode,proto3" json:"barcode,omitempty"`
	VerificationCode string                 `protobuf:"bytes,3,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SecurityFeatures) Reset() {
	*x = SecurityFeatures{}
	mi := &file_proto_ticket_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityFeatures) ProtoMessage() {}

func (x *SecurityFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityFeatures.ProtoReflect.Descriptor instead.
func (*SecurityFeatures) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityFeatures) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *SecurityFeatures) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *SecurityFeatures) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

// IssuerDetails contains information about who issued the ticket
type IssuerDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	AgentCode     string                 `protobuf:"bytes,2,opt,name=agent_code,json=agentCode,proto3" json:"agent_code,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerDetails) Reset() {
	*x = IssuerDetails{}
	mi := &file_proto_ticket_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerDetails) ProtoMessage() {}

func (x *IssuerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerDetails.ProtoReflect.Descriptor instead.
func (*IssuerDetails) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{2}
}

func (x *IssuerDetails) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *IssuerDetails) GetAgentCode() string {
	if x != nil {
		return x.AgentCode
	}
	return ""
}

func (x *IssuerDetails) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// Ticket represents a lottery ticket
type Ticket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SerialNumber     string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	GameCode         string                 `protobuf:"bytes,3,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	GameScheduleId   string                 `protobuf:"bytes,4,opt,name=game_schedule_id,json=gameScheduleId,proto3" json:"game_schedule_id,omitempty"`
	DrawNumber       int32                  `protobuf:"varint,5,opt,name=draw_number,json=drawNumber,proto3" json:"draw_number,omitempty"`
	DrawDate         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=draw_date,json=drawDate,proto3" json:"draw_date,omitempty"`
	SelectedNumbers  []int32                `protobuf:"varint,7,rep,packed,name=selected_numbers,json=selectedNumbers,proto3" json:"selected_numbers,omitempty"`
	BetLines         []*BetLine             `protobuf:"bytes,8,rep,name=bet_lines,json=betLines,proto3" json:"bet_lines,omitempty"`
	IssuerType       string                 `protobuf:"bytes,9,opt,name=issuer_type,json=issuerType,proto3" json:"issuer_type,omitempty"`
	IssuerId         string                 `protobuf:"bytes,10,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	IssuerDetails    *IssuerDetails         `protobuf:"bytes,11,opt,name=issuer_details,json=issuerDetails,proto3" json:"issuer_details,omitempty"`
	CustomerPhone    string                 `protobuf:"bytes,12,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	CustomerEmail    string                 `protobuf:"bytes,13,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	PaymentMethod    string                 `protobuf:"bytes,14,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	UnitPrice        int64                  `protobuf:"varint,15,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalAmount      int64                  `protobuf:"varint,16,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	SecurityHash     string                 `protobuf:"bytes,17,opt,name=security_hash,json=securityHash,proto3" json:"security_hash,omitempty"`
	SecurityFeatures *SecurityFeatures      `protobuf:"bytes,18,opt,name=security_features,json=securityFeatures,proto3" json:"security_features,omitempty"`
	Status           string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	WinningAmount    int64                  `protobuf:"varint,20,opt,name=winning_amount,json=winningAmount,proto3" json:"winning_amount,omitempty"`
	ValidatedAt      *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	CancelledAt      *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	VoidedAt         *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=voided_at,json=voidedAt,proto3" json:"voided_at,omitempty"`
	CancelledReason  string                 `protobuf:"bytes,24,opt,name=cancelled_reason,json=cancelledReason,proto3" json:"cancelled_reason,omitempty"`
	VoidedReason     string                 `protobuf:"bytes,25,opt,name=voided_reason,json=voidedReason,proto3" json:"voided_reason,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BankerNumbers    []int32                `protobuf:"varint,28,rep,packed,name=banker_numbers,json=bankerNumbers,proto3" json:"banker_numbers,omitempty"`
	OpposedNumbers   []int32                `protobuf:"varint,29,rep,packed,name=opposed_numbers,json=opposedNumbers,proto3" json:"opposed_numbers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_proto_ticket_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{3}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Ticket) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *Ticket) GetGameScheduleId() string {
	if x != nil {
		return x.GameScheduleId
	}
	return ""
}

func (x *Ticket) GetDrawNumber() int32 {
	if x != nil {
		return x.DrawNumber
	}
	return 0
}

func (x *Ticket) GetDrawDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DrawDate
	}
	return nil
}

func (x *Ticket) GetSelectedNumbers() []int32 {
	if x != nil {
		return x.SelectedNumbers
	}
	return nil
}

func (x *Ticket) GetBetLines() []*BetLine {
	if x != nil {
		return x.BetLines
	}
	return nil
}

func (x *Ticket) GetIssuerType() string {
	if x != nil {
		return x.IssuerType
	}
	return ""
}

func (x *Ticket) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *Ticket) GetIssuerDetails() *IssuerDetails {
	if x != nil {
		return x.IssuerDetails
	}
	return nil
}

func (x *Ticket) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *Ticket) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *Ticket) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Ticket) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *Ticket) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Ticket) GetSecurityHash() string {
	if x != nil {
		return x.SecurityHash
	}
	return ""
}

func (x *Ticket) GetSecurityFeatures() *SecurityFeatures {
	if x != nil {
		return x.SecurityFeatures
	}
	return nil
}

func (x *Ticket) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ticket) GetWinningAmount() int64 {
	if x != nil {
		return x.WinningAmount
	}
	return 0
}

func (x *Ticket) GetValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidatedAt
	}
	return nil
}

func (x *Ticket) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *Ticket) GetVoidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VoidedAt
	}
	return nil
}

func (x *Ticket) GetCancelledReason() string {
	if x != nil {
		return x.CancelledReason
	}
	return ""
}

func (x *Ticket) GetVoidedReason() string {
	if x != nil {
		return x.VoidedReason
	}
	return ""
}

func (x *Ticket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ticket) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Ticket) GetBankerNumbers() []int32 {
	if x != nil {
		return x.BankerNumbers
	}
	return nil
}

func (x *Ticket) GetOpposedNumbers() []int32 {
	if x != nil {
		return x.OpposedNumbers
	}
	return nil
}

// IssueTicketRequest contains the information needed to issue a new ticket
type IssueTicketRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameCode        string                 `protobuf:"bytes,1,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	GameScheduleId  string                 `protobuf:"bytes,2,opt,name=game_schedule_id,json=gameScheduleId,proto3" json:"game_schedule_id,omitempty"`
	DrawNumber      int32                  `protobuf:"varint,3,opt,name=draw_number,json=drawNumber,proto3" json:"draw_number,omitempty"`
	SelectedNumbers []int32                `protobuf:"varint,4,rep,packed,name=selected_numbers,json=selectedNumbers,proto3" json:"selected_numbers,omitempty"`
	BetLines        []*BetLine             `protobuf:"bytes,5,rep,name=bet_lines,json=betLines,proto3" json:"bet_lines,omitempty"`
	IssuerType      string                 `protobuf:"bytes,6,opt,name=issuer_type,json=issuerType,proto3" json:"issuer_type,omitempty"`
	IssuerId        string                 `protobuf:"bytes,7,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	IssuerDetails   *IssuerDetails         `protobuf:"bytes,8,opt,name=issuer_details,json=issuerDetails,proto3" json:"issuer_details,omitempty"`
	CustomerPhone   string                 `protobuf:"bytes,9,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	CustomerEmail   string                 `protobuf:"bytes,10,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,11,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueTicketRequest) Reset() {
	*x = IssueTicketRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTicketRequest) ProtoMessage() {}

func (x *IssueTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTicketRequest.ProtoReflect.Descriptor instead.
func (*IssueTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{4}
}

func (x *IssueTicketRequest) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *IssueTicketRequest) GetGameScheduleId() string {
	if x != nil {
		return x.GameScheduleId
	}
	return ""
}

func (x *IssueTicketRequest) GetDrawNumber() int32 {
	if x != nil {
		return x.DrawNumber
	}
	return 0
}

func (x *IssueTicketRequest) GetSelectedNumbers() []int32 {
	if x != nil {
		return x.SelectedNumbers
	}
	return nil
}

func (x *IssueTicketRequest) GetBetLines() []*BetLine {
	if x != nil {
		return x.BetLines
	}
	return nil
}

func (x *IssueTicketRequest) GetIssuerType() string {
	if x != nil {
		return x.IssuerType
	}
	return ""
}

func (x *IssueTicketRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *IssueTicketRequest) GetIssuerDetails() *IssuerDetails {
	if x != nil {
		return x.IssuerDetails
	}
	return nil
}

func (x *IssueTicketRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *IssueTicketRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *IssueTicketRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

// IssueTicketResponse contains the newly issued ticket
type IssueTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTicketResponse) Reset() {
	*x = IssueTicketResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTicketResponse) ProtoMessage() {}

func (x *IssueTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTicketResponse.ProtoReflect.Descriptor instead.
func (*IssueTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{5}
}

func (x *IssueTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// GetTicketRequest requests a ticket by ID
type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

// GetTicketResponse returns a ticket
type GetTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketResponse) Reset() {
	*x = GetTicketResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketResponse) ProtoMessage() {}

func (x *GetTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketResponse.ProtoReflect.Descriptor instead.
func (*GetTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// GetTicketBySerialRequest requests a ticket by serial number
type GetTicketBySerialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketBySerialRequest) Reset() {
	*x = GetTicketBySerialRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketBySerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketBySerialRequest) ProtoMessage() {}

func (x *GetTicketBySerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketBySerialRequest.ProtoReflect.Descriptor instead.
func (*GetTicketBySerialRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTicketBySerialRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

// GetTicketBySerialResponse returns a ticket
type GetTicketBySerialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketBySerialResponse) Reset() {
	*x = GetTicketBySerialResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketBySerialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketBySerialResponse) ProtoMessage() {}

func (x *GetTicketBySerialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketBySerialResponse.ProtoReflect.Descriptor instead.
func (*GetTicketBySerialResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetTicketBySerialResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// TicketFilter defines filtering options for listing tickets
type TicketFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	GameCode      string                 `protobuf:"bytes,2,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	DrawNumber    int32                  `protobuf:"varint,3,opt,name=draw_number,json=drawNumber,proto3" json:"draw_number,omitempty"`
	IssuerType    string                 `protobuf:"bytes,4,opt,name=issuer_type,json=issuerType,proto3" json:"issuer_type,omitempty"`
	IssuerId      string                 `protobuf:"bytes,5,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketFilter) Reset() {
	*x = TicketFilter{}
	mi := &file_proto_ticket_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketFilter) ProtoMessage() {}

func (x *TicketFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketFilter.ProtoReflect.Descriptor instead.
func (*TicketFilter) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{10}
}

func (x *TicketFilter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TicketFilter) GetGameCode() string {
	if x != nil {
		return x.GameCode
	}
	return ""
}

func (x *TicketFilter) GetDrawNumber() int32 {
	if x != nil {
		return x.DrawNumber
	}
	return 0
}

func (x *TicketFilter) GetIssuerType() string {
	if x != nil {
		return x.IssuerType
	}
	return ""
}

func (x *TicketFilter) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *TicketFilter) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *TicketFilter) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

// ListTicketsRequest requests a paginated list of tickets
type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *TicketFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListTicketsRequest) GetFilter() *TicketFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListTicketsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTicketsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListTicketsResponse returns a paginated list of tickets
type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *ListTicketsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTicketsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTicketsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ValidateTicketRequest validates a ticket
type ValidateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ValidatorId   string                 `protobuf:"bytes,2,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	ValidatorType string                 `protobuf:"bytes,3,opt,name=validator_type,json=validatorType,proto3" json:"validator_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketRequest) Reset() {
	*x = ValidateTicketRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketRequest) ProtoMessage() {}

func (x *ValidateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketRequest.ProtoReflect.Descriptor instead.
func (*ValidateTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{13}
}

func (x *ValidateTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ValidateTicketRequest) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *ValidateTicketRequest) GetValidatorType() string {
	if x != nil {
		return x.ValidatorType
	}
	return ""
}

// ValidateTicketResponse returns the validated ticket
type ValidateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	WinningAmount int64                  `protobuf:"varint,2,opt,name=winning_amount,json=winningAmount,proto3" json:"winning_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketResponse) Reset() {
	*x = ValidateTicketResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketResponse) ProtoMessage() {}

func (x *ValidateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketResponse.ProtoReflect.Descriptor instead.
func (*ValidateTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *ValidateTicketResponse) GetWinningAmount() int64 {
	if x != nil {
		return x.WinningAmount
	}
	return 0
}

// CancelTicketRequest cancels a ticket
type CancelTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,3,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTicketRequest) Reset() {
	*x = CancelTicketRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketRequest) ProtoMessage() {}

func (x *CancelTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketRequest.ProtoReflect.Descriptor instead.
func (*CancelTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{15}
}

func (x *CancelTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CancelTicketRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelTicketRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

// CancelTicketResponse returns the cancelled ticket
type CancelTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTicketResponse) Reset() {
	*x = CancelTicketResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTicketResponse) ProtoMessage() {}

func (x *CancelTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTicketResponse.ProtoReflect.Descriptor instead.
func (*CancelTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{16}
}

func (x *CancelTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// VoidTicketRequest voids a ticket
type VoidTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	VoidedBy      string                 `protobuf:"bytes,3,opt,name=voided_by,json=voidedBy,proto3" json:"voided_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidTicketRequest) Reset() {
	*x = VoidTicketRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidTicketRequest) ProtoMessage() {}

func (x *VoidTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidTicketRequest.ProtoReflect.Descriptor instead.
func (*VoidTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{17}
}

func (x *VoidTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *VoidTicketRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VoidTicketRequest) GetVoidedBy() string {
	if x != nil {
		return x.VoidedBy
	}
	return ""
}

// VoidTicketResponse returns the voided ticket
type VoidTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidTicketResponse) Reset() {
	*x = VoidTicketResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidTicketResponse) ProtoMessage() {}

func (x *VoidTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidTicketResponse.ProtoReflect.Descriptor instead.
func (*VoidTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{18}
}

func (x *VoidTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// ReprintTicketRequest requests a ticket reprint
type ReprintTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ReprintedBy   string                 `protobuf:"bytes,2,opt,name=reprinted_by,json=reprintedBy,proto3" json:"reprinted_by,omitempty"`
	TerminalId    string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprintTicketRequest) Reset() {
	*x = ReprintTicketRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprintTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprintTicketRequest) ProtoMessage() {}

func (x *ReprintTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprintTicketRequest.ProtoReflect.Descriptor instead.
func (*ReprintTicketRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{19}
}

func (x *ReprintTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ReprintTicketRequest) GetReprintedBy() string {
	if x != nil {
		return x.ReprintedBy
	}
	return ""
}

func (x *ReprintTicketRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

// ReprintTicketResponse returns the reprinted ticket
type ReprintTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprintTicketResponse) Reset() {
	*x = ReprintTicketResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprintTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprintTicketResponse) ProtoMessage() {}

func (x *ReprintTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprintTicketResponse.ProtoReflect.Descriptor instead.
func (*ReprintTicketResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{20}
}

func (x *ReprintTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// CheckWinningsRequest checks ticket winnings
type CheckWinningsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWinningsRequest) Reset() {
	*x = CheckWinningsRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWinningsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWinningsRequest) ProtoMessage() {}

func (x *CheckWinningsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWinningsRequest.ProtoReflect.Descriptor instead.
func (*CheckWinningsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{21}
}

func (x *CheckWinningsRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

// CheckWinningsResponse returns winning information
type CheckWinningsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasWinnings   bool                   `protobuf:"varint,1,opt,name=has_winnings,json=hasWinnings,proto3" json:"has_winnings,omitempty"`
	WinningAmount int64                  `protobuf:"varint,2,opt,name=winning_amount,json=winningAmount,proto3" json:"winning_amount,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckWinningsResponse) Reset() {
	*x = CheckWinningsResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWinningsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWinningsResponse) ProtoMessage() {}

func (x *CheckWinningsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWinningsResponse.ProtoReflect.Descriptor instead.
func (*CheckWinningsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{22}
}

func (x *CheckWinningsResponse) GetHasWinnings() bool {
	if x != nil {
		return x.HasWinnings
	}
	return false
}

func (x *CheckWinningsResponse) GetWinningAmount() int64 {
	if x != nil {
		return x.WinningAmount
	}
	return 0
}

func (x *CheckWinningsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// AgentPerformance represents performance metrics for a single agent
type AgentPerformance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentCode       string                 `protobuf:"bytes,2,opt,name=agent_code,json=agentCode,proto3" json:"agent_code,omitempty"`
	AgentName       string                 `protobuf:"bytes,3,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	TotalRevenue    int64                  `protobuf:"varint,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`             // in pesewas
	TotalRevenueGhs float64                `protobuf:"fixed64,5,opt,name=total_revenue_ghs,json=totalRevenueGhs,proto3" json:"total_revenue_ghs,omitempty"` // in GHS
	TotalTickets    int64                  `protobuf:"varint,6,opt,name=total_tickets,json=totalTickets,proto3" json:"total_tickets,omitempty"`
	RetailerCount   int32                  `protobuf:"varint,7,opt,name=retailer_count,json=retailerCount,proto3" json:"retailer_count,omitempty"` // number of retailers under this agent
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentPerformance) Reset() {
	*x = AgentPerformance{}
	mi := &file_proto_ticket_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPerformance) ProtoMessage() {}

func (x *AgentPerformance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPerformance.ProtoReflect.Descriptor instead.
func (*AgentPerformance) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{23}
}

func (x *AgentPerformance) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentPerformance) GetAgentCode() string {
	if x != nil {
		return x.AgentCode
	}
	return ""
}

func (x *AgentPerformance) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentPerformance) GetTotalRevenue() int64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *AgentPerformance) GetTotalRevenueGhs() float64 {
	if x != nil {
		return x.TotalRevenueGhs
	}
	return 0
}

func (x *AgentPerformance) GetTotalTickets() int64 {
	if x != nil {
		return x.TotalTickets
	}
	return 0
}

func (x *AgentPerformance) GetRetailerCount() int32 {
	if x != nil {
		return x.RetailerCount
	}
	return 0
}

// GetTopPerformingAgentsRequest requests top performing agents
type GetTopPerformingAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`     // optional, format: YYYY-MM-DD, defaults to today
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // number of agents to return, default 10
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"` // period type: "daily", "monthly", "yearly", default "monthly"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPerformingAgentsRequest) Reset() {
	*x = GetTopPerformingAgentsRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPerformingAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPerformingAgentsRequest) ProtoMessage() {}

func (x *GetTopPerformingAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPerformingAgentsRequest.ProtoReflect.Descriptor instead.
func (*GetTopPerformingAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetTopPerformingAgentsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetTopPerformingAgentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopPerformingAgentsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// GetTopPerformingAgentsResponse returns top performing agents
type GetTopPerformingAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentPerformance    `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // the period that was queried
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`     // the date that was queried
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopPerformingAgentsResponse) Reset() {
	*x = GetTopPerformingAgentsResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopPerformingAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPerformingAgentsResponse) ProtoMessage() {}

func (x *GetTopPerformingAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPerformingAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetTopPerformingAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetTopPerformingAgentsResponse) GetAgents() []*AgentPerformance {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *GetTopPerformingAgentsResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetTopPerformingAgentsResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// GetAllTicketsForDrawRequest requests all tickets for a specific draw
// This is an internal service-to-service call for draw processing
type GetAllTicketsForDrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrawId        string                 `protobuf:"bytes,1,opt,name=draw_id,json=drawId,proto3" json:"draw_id,omitempty"` // UUID of the draw
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`               // optional ticket status filter (e.g., "issued")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTicketsForDrawRequest) Reset() {
	*x = GetAllTicketsForDrawRequest{}
	mi := &file_proto_ticket_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTicketsForDrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTicketsForDrawRequest) ProtoMessage() {}

func (x *GetAllTicketsForDrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTicketsForDrawRequest.ProtoReflect.Descriptor instead.
func (*GetAllTicketsForDrawRequest) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetAllTicketsForDrawRequest) GetDrawId() string {
	if x != nil {
		return x.DrawId
	}
	return ""
}

func (x *GetAllTicketsForDrawRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetAllTicketsForDrawResponse returns all tickets for the draw
type GetAllTicketsForDrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // total number of tickets found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTicketsForDrawResponse) Reset() {
	*x = GetAllTicketsForDrawResponse{}
	mi := &file_proto_ticket_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTicketsForDrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTicketsForDrawResponse) ProtoMessage() {}

func (x *GetAllTicketsForDrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ticket_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTicketsForDrawResponse.ProtoReflect.Descriptor instead.
func (*GetAllTicketsForDrawResponse) Descriptor() ([]byte, []int) {
	return file_proto_ticket_service_proto_rawDescGZIP(), []int{27}
}

func (x *GetAllTicketsForDrawResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *GetAllTicketsForDrawResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_ticket_service_proto protoreflect.FileDescriptor

const file_proto_ticket_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/ticket_service.proto\x12\x06ticket\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n" +
	"\aBetLine\x12\x1f\n" +
	"\vline_number\x18\x01 \x01(\x05R\n" +
	"lineNumber\x12\x19\n" +
	"\bbet_type\x18\x02 \x01(\tR\abetType\x12\x18\n" +
	"\anumbers\x18\x03 \x03(\x05R\anumbers\x12\x16\n" +
	"\x06banker\x18\x04 \x03(\x05R\x06banker\x12\x18\n" +
	"\aopposed\x18\x05 \x03(\x05R\aopposed\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\"r\n" +
	"\x10SecurityFeatures\x12\x17\n" +
	"\aqr_code\x18\x01 \x01(\tR\x06qrCode\x12\x18\n" +
	"\abarcode\x18\x02 \x01(\tR\abarcode\x12+\n" +
	"\x11verification_code\x18\x03 \x01(\tR\x10verificationCode\"k\n" +
	"\rIssuerDetails\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x1d\n" +
	"\n" +
	"agent_code\x18\x02 \x01(\tR\tagentCode\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"\xe2\t\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1b\n" +
	"\tgame_code\x18\x03 \x01(\tR\bgameCode\x12(\n" +
	"\x10game_schedule_id\x18\x04 \x01(\tR\x0egameScheduleId\x12\x1f\n" +
	"\vdraw_number\x18\x05 \x01(\x05R\n" +
	"drawNumber\x127\n" +
	"\tdraw_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdrawDate\x12)\n" +
	"\x10selected_numbers\x18\a \x03(\x05R\x0fselectedNumbers\x12,\n" +
	"\tbet_lines\x18\b \x03(\v2\x0f.ticket.BetLineR\bbetLines\x12\x1f\n" +
	"\vissuer_type\x18\t \x01(\tR\n" +
	"issuerType\x12\x1b\n" +
	"\tissuer_id\x18\n" +
	" \x01(\tR\bissuerId\x12<\n" +
	"\x0eissuer_details\x18\v \x01(\v2\x15.ticket.IssuerDetailsR\rissuerDetails\x12%\n" +
	"\x0ecustomer_phone\x18\f \x01(\tR\rcustomerPhone\x12%\n" +
	"\x0ecustomer_email\x18\r \x01(\tR\rcustomerEmail\x12%\n" +
	"\x0epayment_method\x18\x0e \x01(\tR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x0f \x01(\x03R\tunitPrice\x12!\n" +
	"\ftotal_amount\x18\x10 \x01(\x03R\vtotalAmount\x12#\n" +
	"\rsecurity_hash\x18\x11 \x01(\tR\fsecurityHash\x12E\n" +
	"\x11security_features\x18\x12 \x01(\v2\x18.ticket.SecurityFeaturesR\x10securityFeatures\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\x12%\n" +
	"\x0ewinning_amount\x18\x14 \x01(\x03R\rwinningAmount\x12=\n" +
	"\fvalidated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\vvalidatedAt\x12=\n" +
	"\fcancelled_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x127\n" +
	"\tvoided_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\bvoidedAt\x12)\n" +
	"\x10cancelled_reason\x18\x18 \x01(\tR\x0fcancelledReason\x12#\n" +
	"\rvoided_reason\x18\x19 \x01(\tR\fvoidedReason\x129\n" +
	"\n" +
	"created_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0ebanker_numbers\x18\x1c \x03(\x05R\rbankerNumbers\x12'\n" +
	"\x0fopposed_numbers\x18\x1d \x03(\x05R\x0eopposedNumbers\"\xc6\x03\n" +
	"\x12IssueTicketRequest\x12\x1b\n" +
	"\tgame_code\x18\x01 \x01(\tR\bgameCode\x12(\n" +
	"\x10game_schedule_id\x18\x02 \x01(\tR\x0egameScheduleId\x12\x1f\n" +
	"\vdraw_number\x18\x03 \x01(\x05R\n" +
	"drawNumber\x12)\n" +
	"\x10selected_numbers\x18\x04 \x03(\x05R\x0fselectedNumbers\x12,\n" +
	"\tbet_lines\x18\x05 \x03(\v2\x0f.ticket.BetLineR\bbetLines\x12\x1f\n" +
	"\vissuer_type\x18\x06 \x01(\tR\n" +
	"issuerType\x12\x1b\n" +
	"\tissuer_id\x18\a \x01(\tR\bissuerId\x12<\n" +
	"\x0eissuer_details\x18\b \x01(\v2\x15.ticket.IssuerDetailsR\rissuerDetails\x12%\n" +
	"\x0ecustomer_phone\x18\t \x01(\tR\rcustomerPhone\x12%\n" +
	"\x0ecustomer_email\x18\n" +
	" \x01(\tR\rcustomerEmail\x12%\n" +
	"\x0epayment_method\x18\v \x01(\tR\rpaymentMethod\"=\n" +
	"\x13IssueTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"/\n" +
	"\x10GetTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\";\n" +
	"\x11GetTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"?\n" +
	"\x18GetTicketBySerialRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\"C\n" +
	"\x19GetTicketBySerialResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"\x94\x02\n" +
	"\fTicketFilter\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tgame_code\x18\x02 \x01(\tR\bgameCode\x12\x1f\n" +
	"\vdraw_number\x18\x03 \x01(\x05R\n" +
	"drawNumber\x12\x1f\n" +
	"\vissuer_type\x18\x04 \x01(\tR\n" +
	"issuerType\x12\x1b\n" +
	"\tissuer_id\x18\x05 \x01(\tR\bissuerId\x129\n" +
	"\n" +
	"start_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"s\n" +
	"\x12ListTicketsRequest\x12,\n" +
	"\x06filter\x18\x01 \x01(\v2\x14.ticket.TicketFilterR\x06filter\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x86\x01\n" +
	"\x13ListTicketsResponse\x12(\n" +
	"\atickets\x18\x01 \x03(\v2\x0e.ticket.TicketR\atickets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"~\n" +
	"\x15ValidateTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12!\n" +
	"\fvalidator_id\x18\x02 \x01(\tR\vvalidatorId\x12%\n" +
	"\x0evalidator_type\x18\x03 \x01(\tR\rvalidatorType\"g\n" +
	"\x16ValidateTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\x12%\n" +
	"\x0ewinning_amount\x18\x02 \x01(\x03R\rwinningAmount\"m\n" +
	"\x13CancelTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fcancelled_by\x18\x03 \x01(\tR\vcancelledBy\">\n" +
	"\x14CancelTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"e\n" +
	"\x11VoidTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\tvoided_by\x18\x03 \x01(\tR\bvoidedBy\"<\n" +
	"\x12VoidTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"w\n" +
	"\x14ReprintTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12!\n" +
	"\freprinted_by\x18\x02 \x01(\tR\vreprintedBy\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\"?\n" +
	"\x15ReprintTicketResponse\x12&\n" +
	"\x06ticket\x18\x01 \x01(\v2\x0e.ticket.TicketR\x06ticket\"3\n" +
	"\x14CheckWinningsRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"y\n" +
	"\x15CheckWinningsResponse\x12!\n" +
	"\fhas_winnings\x18\x01 \x01(\bR\vhasWinnings\x12%\n" +
	"\x0ewinning_amount\x18\x02 \x01(\x03R\rwinningAmount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x88\x02\n" +
	"\x10AgentPerformance\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_code\x18\x02 \x01(\tR\tagentCode\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x03 \x01(\tR\tagentName\x12#\n" +
	"\rtotal_revenue\x18\x04 \x01(\x03R\ftotalRevenue\x12*\n" +
	"\x11total_revenue_ghs\x18\x05 \x01(\x01R\x0ftotalRevenueGhs\x12#\n" +
	"\rtotal_tickets\x18\x06 \x01(\x03R\ftotalTickets\x12%\n" +
	"\x0eretailer_count\x18\a \x01(\x05R\rretailerCount\"a\n" +
	"\x1dGetTopPerformingAgentsRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\"~\n" +
	"\x1eGetTopPerformingAgentsResponse\x120\n" +
	"\x06agents\x18\x01 \x03(\v2\x18.ticket.AgentPerformanceR\x06agents\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"N\n" +
	"\x1bGetAllTicketsForDrawRequest\x12\x17\n" +
	"\adraw_id\x18\x01 \x01(\tR\x06drawId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"^\n" +
	"\x1cGetAllTicketsForDrawResponse\x12(\n" +
	"\atickets\x18\x01 \x03(\v2\x0e.ticket.TicketR\atickets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x84\a\n" +
	"\rTicketService\x12F\n" +
	"\vIssueTicket\x12\x1a.ticket.IssueTicketRequest\x1a\x1b.ticket.IssueTicketResponse\x12@\n" +
	"\tGetTicket\x12\x18.ticket.GetTicketRequest\x1a\x19.ticket.GetTicketResponse\x12X\n" +
	"\x11GetTicketBySerial\x12 .ticket.GetTicketBySerialRequest\x1a!.ticket.GetTicketBySerialResponse\x12F\n" +
	"\vListTickets\x12\x1a.ticket.ListTicketsRequest\x1a\x1b.ticket.ListTicketsResponse\x12O\n" +
	"\x0eValidateTicket\x12\x1d.ticket.ValidateTicketRequest\x1a\x1e.ticket.ValidateTicketResponse\x12I\n" +
	"\fCancelTicket\x12\x1b.ticket.CancelTicketRequest\x1a\x1c.ticket.CancelTicketResponse\x12C\n" +
	"\n" +
	"VoidTicket\x12\x19.ticket.VoidTicketRequest\x1a\x1a.ticket.VoidTicketResponse\x12L\n" +
	"\rReprintTicket\x12\x1c.ticket.ReprintTicketRequest\x1a\x1d.ticket.ReprintTicketResponse\x12L\n" +
	"\rCheckWinnings\x12\x1c.ticket.CheckWinningsRequest\x1a\x1d.ticket.CheckWinningsResponse\x12g\n" +
	"\x16GetTopPerformingAgents\x12%.ticket.GetTopPerformingAgentsRequest\x1a&.ticket.GetTopPerformingAgentsResponse\x12a\n" +
	"\x14GetAllTicketsForDraw\x12#.ticket.GetAllTicketsForDrawRequest\x1a$.ticket.GetAllTicketsForDrawResponseBOZMgithub.com/randco/randco-microservices/services/service-ticket/proto;ticketpbb\x06proto3"

var (
	file_proto_ticket_service_proto_rawDescOnce sync.Once
	file_proto_ticket_service_proto_rawDescData []byte
)

func file_proto_ticket_service_proto_rawDescGZIP() []byte {
	file_proto_ticket_service_proto_rawDescOnce.Do(func() {
		file_proto_ticket_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ticket_service_proto_rawDesc), len(file_proto_ticket_service_proto_rawDesc)))
	})
	return file_proto_ticket_service_proto_rawDescData
}

var file_proto_ticket_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_ticket_service_proto_goTypes = []any{
	(*BetLine)(nil),                        // 0: ticket.BetLine
	(*SecurityFeatures)(nil),               // 1: ticket.SecurityFeatures
	(*IssuerDetails)(nil),                  // 2: ticket.IssuerDetails
	(*Ticket)(nil),                         // 3: ticket.Ticket
	(*IssueTicketRequest)(nil),             // 4: ticket.IssueTicketRequest
	(*IssueTicketResponse)(nil),            // 5: ticket.IssueTicketResponse
	(*GetTicketRequest)(nil),               // 6: ticket.GetTicketRequest
	(*GetTicketResponse)(nil),              // 7: ticket.GetTicketResponse
	(*GetTicketBySerialRequest)(nil),       // 8: ticket.GetTicketBySerialRequest
	(*GetTicketBySerialResponse)(nil),      // 9: ticket.GetTicketBySerialResponse
	(*TicketFilter)(nil),                   // 10: ticket.TicketFilter
	(*ListTicketsRequest)(nil),             // 11: ticket.ListTicketsRequest
	(*ListTicketsResponse)(nil),            // 12: ticket.ListTicketsResponse
	(*ValidateTicketRequest)(nil),          // 13: ticket.ValidateTicketRequest
	(*ValidateTicketResponse)(nil),         // 14: ticket.ValidateTicketResponse
	(*CancelTicketRequest)(nil),            // 15: ticket.CancelTicketRequest
	(*CancelTicketResponse)(nil),           // 16: ticket.CancelTicketResponse
	(*VoidTicketRequest)(nil),              // 17: ticket.VoidTicketRequest
	(*VoidTicketResponse)(nil),             // 18: ticket.VoidTicketResponse
	(*ReprintTicketRequest)(nil),           // 19: ticket.ReprintTicketRequest
	(*ReprintTicketResponse)(nil),          // 20: ticket.ReprintTicketResponse
	(*CheckWinningsRequest)(nil),           // 21: ticket.CheckWinningsRequest
	(*CheckWinningsResponse)(nil),          // 22: ticket.CheckWinningsResponse
	(*AgentPerformance)(nil),               // 23: ticket.AgentPerformance
	(*GetTopPerformingAgentsRequest)(nil),  // 24: ticket.GetTopPerformingAgentsRequest
	(*GetTopPerformingAgentsResponse)(nil), // 25: ticket.GetTopPerformingAgentsResponse
	(*GetAllTicketsForDrawRequest)(nil),    // 26: ticket.GetAllTicketsForDrawRequest
	(*GetAllTicketsForDrawResponse)(nil),   // 27: ticket.GetAllTicketsForDrawResponse
	(*timestamppb.Timestamp)(nil),          // 28: google.protobuf.Timestamp
}
var file_proto_ticket_service_proto_depIdxs = []int32{
	28, // 0: ticket.Ticket.draw_date:type_name -> google.protobuf.Timestamp
	0,  // 1: ticket.Ticket.bet_lines:type_name -> ticket.BetLine
	2,  // 2: ticket.Ticket.issuer_details:type_name -> ticket.IssuerDetails
	1,  // 3: ticket.Ticket.security_features:type_name -> ticket.SecurityFeatures
	28, // 4: ticket.Ticket.validated_at:type_name -> google.protobuf.Timestamp
	28, // 5: ticket.Ticket.cancelled_at:type_name -> google.protobuf.Timestamp
	28, // 6: ticket.Ticket.voided_at:type_name -> google.protobuf.Timestamp
	28, // 7: ticket.Ticket.created_at:type_name -> google.protobuf.Timestamp
	28, // 8: ticket.Ticket.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: ticket.IssueTicketRequest.bet_lines:type_name -> ticket.BetLine
	2,  // 10: ticket.IssueTicketRequest.issuer_details:type_name -> ticket.IssuerDetails
	3,  // 11: ticket.IssueTicketResponse.ticket:type_name -> ticket.Ticket
	3,  // 12: ticket.GetTicketResponse.ticket:type_name -> ticket.Ticket
	3,  // 13: ticket.GetTicketBySerialResponse.ticket:type_name -> ticket.Ticket
	28, // 14: ticket.TicketFilter.start_date:type_name -> google.protobuf.Timestamp
	28, // 15: ticket.TicketFilter.end_date:type_name -> google.protobuf.Timestamp
	10, // 16: ticket.ListTicketsRequest.filter:type_name -> ticket.TicketFilter
	3,  // 17: ticket.ListTicketsResponse.tickets:type_name -> ticket.Ticket
	3,  // 18: ticket.ValidateTicketResponse.ticket:type_name -> ticket.Ticket
	3,  // 19: ticket.CancelTicketResponse.ticket:type_name -> ticket.Ticket
	3,  // 20: ticket.VoidTicketResponse.ticket:type_name -> ticket.Ticket
	3,  // 21: ticket.ReprintTicketResponse.ticket:type_name -> ticket.Ticket
	23, // 22: ticket.GetTopPerformingAgentsResponse.agents:type_name -> ticket.AgentPerformance
	3,  // 23: ticket.GetAllTicketsForDrawResponse.tickets:type_name -> ticket.Ticket
	4,  // 24: ticket.TicketService.IssueTicket:input_type -> ticket.IssueTicketRequest
	6,  // 25: ticket.TicketService.GetTicket:input_type -> ticket.GetTicketRequest
	8,  // 26: ticket.TicketService.GetTicketBySerial:input_type -> ticket.GetTicketBySerialRequest
	11, // 27: ticket.TicketService.ListTickets:input_type -> ticket.ListTicketsRequest
	13, // 28: ticket.TicketService.ValidateTicket:input_type -> ticket.ValidateTicketRequest
	15, // 29: ticket.TicketService.CancelTicket:input_type -> ticket.CancelTicketRequest
	17, // 30: ticket.TicketService.VoidTicket:input_type -> ticket.VoidTicketRequest
	19, // 31: ticket.TicketService.ReprintTicket:input_type -> ticket.ReprintTicketRequest
	21, // 32: ticket.TicketService.CheckWinnings:input_type -> ticket.CheckWinningsRequest
	24, // 33: ticket.TicketService.GetTopPerformingAgents:input_type -> ticket.GetTopPerformingAgentsRequest
	26, // 34: ticket.TicketService.GetAllTicketsForDraw:input_type -> ticket.GetAllTicketsForDrawRequest
	5,  // 35: ticket.TicketService.IssueTicket:output_type -> ticket.IssueTicketResponse
	7,  // 36: ticket.TicketService.GetTicket:output_type -> ticket.GetTicketResponse
	9,  // 37: ticket.TicketService.GetTicketBySerial:output_type -> ticket.GetTicketBySerialResponse
	12, // 38: ticket.TicketService.ListTickets:output_type -> ticket.ListTicketsResponse
	14, // 39: ticket.TicketService.ValidateTicket:output_type -> ticket.ValidateTicketResponse
	16, // 40: ticket.TicketService.CancelTicket:output_type -> ticket.CancelTicketResponse
	18, // 41: ticket.TicketService.VoidTicket:output_type -> ticket.VoidTicketResponse
	20, // 42: ticket.TicketService.ReprintTicket:output_type -> ticket.ReprintTicketResponse
	22, // 43: ticket.TicketService.CheckWinnings:output_type -> ticket.CheckWinningsResponse
	25, // 44: ticket.TicketService.GetTopPerformingAgents:output_type -> ticket.GetTopPerformingAgentsResponse
	27, // 45: ticket.TicketService.GetAllTicketsForDraw:output_type -> ticket.GetAllTicketsForDrawResponse
	35, // [35:46] is the sub-list for method output_type
	24, // [24:35] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_ticket_service_proto_init() }
func file_proto_ticket_service_proto_init() {
	if File_proto_ticket_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ticket_service_proto_rawDesc), len(file_proto_ticket_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ticket_service_proto_goTypes,
		DependencyIndexes: file_proto_ticket_service_proto_depIdxs,
		MessageInfos:      file_proto_ticket_service_proto_msgTypes,
	}.Build()
	File_proto_ticket_service_proto = out.File
	file_proto_ticket_service_proto_goTypes = nil
	file_proto_ticket_service_proto_depIdxs = nil
}
