apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jaeger.selectorLabels" . | nindent 4 }}
  ports:
  - name: ui
    port: {{ .Values.service.ports.ui.port }}
    targetPort: {{ .Values.service.ports.ui.targetPort }}
    protocol: TCP
  - name: collector
    port: {{ .Values.service.ports.collector.port }}
    targetPort: {{ .Values.service.ports.collector.targetPort }}
    protocol: TCP
  - name: otlp-http
    port: {{ .Values.service.ports.otlpHttp.port }}
    targetPort: {{ .Values.service.ports.otlpHttp.targetPort }}
    protocol: TCP
  - name: otlp-grpc
    port: {{ .Values.service.ports.otlpGrpc.port }}
    targetPort: {{ .Values.service.ports.otlpGrpc.targetPort }}
    protocol: TCP