// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/terminal/v1/terminal.proto

package terminalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TerminalService_RegisterTerminal_FullMethodName         = "/terminal.v1.TerminalService/RegisterTerminal"
	TerminalService_GetTerminal_FullMethodName              = "/terminal.v1.TerminalService/GetTerminal"
	TerminalService_UpdateTerminal_FullMethodName           = "/terminal.v1.TerminalService/UpdateTerminal"
	TerminalService_ListTerminals_FullMethodName            = "/terminal.v1.TerminalService/ListTerminals"
	TerminalService_DeleteTerminal_FullMethodName           = "/terminal.v1.TerminalService/DeleteTerminal"
	TerminalService_AssignTerminalToRetailer_FullMethodName = "/terminal.v1.TerminalService/AssignTerminalToRetailer"
	TerminalService_UnassignTerminal_FullMethodName         = "/terminal.v1.TerminalService/UnassignTerminal"
	TerminalService_GetTerminalByRetailer_FullMethodName    = "/terminal.v1.TerminalService/GetTerminalByRetailer"
	TerminalService_UpdateTerminalStatus_FullMethodName     = "/terminal.v1.TerminalService/UpdateTerminalStatus"
	TerminalService_UpdateTerminalHealth_FullMethodName     = "/terminal.v1.TerminalService/UpdateTerminalHealth"
	TerminalService_GetTerminalHealth_FullMethodName        = "/terminal.v1.TerminalService/GetTerminalHealth"
	TerminalService_UpdateTerminalConfig_FullMethodName     = "/terminal.v1.TerminalService/UpdateTerminalConfig"
	TerminalService_GetTerminalConfig_FullMethodName        = "/terminal.v1.TerminalService/GetTerminalConfig"
	TerminalService_ValidateRetailerTerminal_FullMethodName = "/terminal.v1.TerminalService/ValidateRetailerTerminal"
)

// TerminalServiceClient is the client API for TerminalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TerminalService provides terminal management operations
type TerminalServiceClient interface {
	// Terminal CRUD operations
	RegisterTerminal(ctx context.Context, in *RegisterTerminalRequest, opts ...grpc.CallOption) (*RegisterTerminalResponse, error)
	GetTerminal(ctx context.Context, in *GetTerminalRequest, opts ...grpc.CallOption) (*GetTerminalResponse, error)
	UpdateTerminal(ctx context.Context, in *UpdateTerminalRequest, opts ...grpc.CallOption) (*UpdateTerminalResponse, error)
	ListTerminals(ctx context.Context, in *ListTerminalsRequest, opts ...grpc.CallOption) (*ListTerminalsResponse, error)
	DeleteTerminal(ctx context.Context, in *DeleteTerminalRequest, opts ...grpc.CallOption) (*DeleteTerminalResponse, error)
	// Terminal assignment operations
	AssignTerminalToRetailer(ctx context.Context, in *AssignTerminalRequest, opts ...grpc.CallOption) (*AssignTerminalResponse, error)
	UnassignTerminal(ctx context.Context, in *UnassignTerminalRequest, opts ...grpc.CallOption) (*UnassignTerminalResponse, error)
	GetTerminalByRetailer(ctx context.Context, in *GetTerminalByRetailerRequest, opts ...grpc.CallOption) (*GetTerminalByRetailerResponse, error)
	// Terminal status operations
	UpdateTerminalStatus(ctx context.Context, in *UpdateTerminalStatusRequest, opts ...grpc.CallOption) (*UpdateTerminalStatusResponse, error)
	UpdateTerminalHealth(ctx context.Context, in *UpdateTerminalHealthRequest, opts ...grpc.CallOption) (*UpdateTerminalHealthResponse, error)
	GetTerminalHealth(ctx context.Context, in *GetTerminalHealthRequest, opts ...grpc.CallOption) (*GetTerminalHealthResponse, error)
	// Terminal configuration
	UpdateTerminalConfig(ctx context.Context, in *UpdateTerminalConfigRequest, opts ...grpc.CallOption) (*UpdateTerminalConfigResponse, error)
	GetTerminalConfig(ctx context.Context, in *GetTerminalConfigRequest, opts ...grpc.CallOption) (*GetTerminalConfigResponse, error)
	// Terminal validation
	ValidateRetailerTerminal(ctx context.Context, in *ValidateRetailerTerminalRequest, opts ...grpc.CallOption) (*ValidateRetailerTerminalResponse, error)
}

type terminalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerminalServiceClient(cc grpc.ClientConnInterface) TerminalServiceClient {
	return &terminalServiceClient{cc}
}

func (c *terminalServiceClient) RegisterTerminal(ctx context.Context, in *RegisterTerminalRequest, opts ...grpc.CallOption) (*RegisterTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_RegisterTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) GetTerminal(ctx context.Context, in *GetTerminalRequest, opts ...grpc.CallOption) (*GetTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_GetTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) UpdateTerminal(ctx context.Context, in *UpdateTerminalRequest, opts ...grpc.CallOption) (*UpdateTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_UpdateTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) ListTerminals(ctx context.Context, in *ListTerminalsRequest, opts ...grpc.CallOption) (*ListTerminalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTerminalsResponse)
	err := c.cc.Invoke(ctx, TerminalService_ListTerminals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) DeleteTerminal(ctx context.Context, in *DeleteTerminalRequest, opts ...grpc.CallOption) (*DeleteTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_DeleteTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) AssignTerminalToRetailer(ctx context.Context, in *AssignTerminalRequest, opts ...grpc.CallOption) (*AssignTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_AssignTerminalToRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) UnassignTerminal(ctx context.Context, in *UnassignTerminalRequest, opts ...grpc.CallOption) (*UnassignTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_UnassignTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) GetTerminalByRetailer(ctx context.Context, in *GetTerminalByRetailerRequest, opts ...grpc.CallOption) (*GetTerminalByRetailerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerminalByRetailerResponse)
	err := c.cc.Invoke(ctx, TerminalService_GetTerminalByRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) UpdateTerminalStatus(ctx context.Context, in *UpdateTerminalStatusRequest, opts ...grpc.CallOption) (*UpdateTerminalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTerminalStatusResponse)
	err := c.cc.Invoke(ctx, TerminalService_UpdateTerminalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) UpdateTerminalHealth(ctx context.Context, in *UpdateTerminalHealthRequest, opts ...grpc.CallOption) (*UpdateTerminalHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTerminalHealthResponse)
	err := c.cc.Invoke(ctx, TerminalService_UpdateTerminalHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) GetTerminalHealth(ctx context.Context, in *GetTerminalHealthRequest, opts ...grpc.CallOption) (*GetTerminalHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerminalHealthResponse)
	err := c.cc.Invoke(ctx, TerminalService_GetTerminalHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) UpdateTerminalConfig(ctx context.Context, in *UpdateTerminalConfigRequest, opts ...grpc.CallOption) (*UpdateTerminalConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTerminalConfigResponse)
	err := c.cc.Invoke(ctx, TerminalService_UpdateTerminalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) GetTerminalConfig(ctx context.Context, in *GetTerminalConfigRequest, opts ...grpc.CallOption) (*GetTerminalConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerminalConfigResponse)
	err := c.cc.Invoke(ctx, TerminalService_GetTerminalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalServiceClient) ValidateRetailerTerminal(ctx context.Context, in *ValidateRetailerTerminalRequest, opts ...grpc.CallOption) (*ValidateRetailerTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRetailerTerminalResponse)
	err := c.cc.Invoke(ctx, TerminalService_ValidateRetailerTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerminalServiceServer is the server API for TerminalService service.
// All implementations must embed UnimplementedTerminalServiceServer
// for forward compatibility.
//
// TerminalService provides terminal management operations
type TerminalServiceServer interface {
	// Terminal CRUD operations
	RegisterTerminal(context.Context, *RegisterTerminalRequest) (*RegisterTerminalResponse, error)
	GetTerminal(context.Context, *GetTerminalRequest) (*GetTerminalResponse, error)
	UpdateTerminal(context.Context, *UpdateTerminalRequest) (*UpdateTerminalResponse, error)
	ListTerminals(context.Context, *ListTerminalsRequest) (*ListTerminalsResponse, error)
	DeleteTerminal(context.Context, *DeleteTerminalRequest) (*DeleteTerminalResponse, error)
	// Terminal assignment operations
	AssignTerminalToRetailer(context.Context, *AssignTerminalRequest) (*AssignTerminalResponse, error)
	UnassignTerminal(context.Context, *UnassignTerminalRequest) (*UnassignTerminalResponse, error)
	GetTerminalByRetailer(context.Context, *GetTerminalByRetailerRequest) (*GetTerminalByRetailerResponse, error)
	// Terminal status operations
	UpdateTerminalStatus(context.Context, *UpdateTerminalStatusRequest) (*UpdateTerminalStatusResponse, error)
	UpdateTerminalHealth(context.Context, *UpdateTerminalHealthRequest) (*UpdateTerminalHealthResponse, error)
	GetTerminalHealth(context.Context, *GetTerminalHealthRequest) (*GetTerminalHealthResponse, error)
	// Terminal configuration
	UpdateTerminalConfig(context.Context, *UpdateTerminalConfigRequest) (*UpdateTerminalConfigResponse, error)
	GetTerminalConfig(context.Context, *GetTerminalConfigRequest) (*GetTerminalConfigResponse, error)
	// Terminal validation
	ValidateRetailerTerminal(context.Context, *ValidateRetailerTerminalRequest) (*ValidateRetailerTerminalResponse, error)
	mustEmbedUnimplementedTerminalServiceServer()
}

// UnimplementedTerminalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerminalServiceServer struct{}

func (UnimplementedTerminalServiceServer) RegisterTerminal(context.Context, *RegisterTerminalRequest) (*RegisterTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) GetTerminal(context.Context, *GetTerminalRequest) (*GetTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) UpdateTerminal(context.Context, *UpdateTerminalRequest) (*UpdateTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) ListTerminals(context.Context, *ListTerminalsRequest) (*ListTerminalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTerminals not implemented")
}
func (UnimplementedTerminalServiceServer) DeleteTerminal(context.Context, *DeleteTerminalRequest) (*DeleteTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) AssignTerminalToRetailer(context.Context, *AssignTerminalRequest) (*AssignTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignTerminalToRetailer not implemented")
}
func (UnimplementedTerminalServiceServer) UnassignTerminal(context.Context, *UnassignTerminalRequest) (*UnassignTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) GetTerminalByRetailer(context.Context, *GetTerminalByRetailerRequest) (*GetTerminalByRetailerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTerminalByRetailer not implemented")
}
func (UnimplementedTerminalServiceServer) UpdateTerminalStatus(context.Context, *UpdateTerminalStatusRequest) (*UpdateTerminalStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTerminalStatus not implemented")
}
func (UnimplementedTerminalServiceServer) UpdateTerminalHealth(context.Context, *UpdateTerminalHealthRequest) (*UpdateTerminalHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTerminalHealth not implemented")
}
func (UnimplementedTerminalServiceServer) GetTerminalHealth(context.Context, *GetTerminalHealthRequest) (*GetTerminalHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTerminalHealth not implemented")
}
func (UnimplementedTerminalServiceServer) UpdateTerminalConfig(context.Context, *UpdateTerminalConfigRequest) (*UpdateTerminalConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTerminalConfig not implemented")
}
func (UnimplementedTerminalServiceServer) GetTerminalConfig(context.Context, *GetTerminalConfigRequest) (*GetTerminalConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTerminalConfig not implemented")
}
func (UnimplementedTerminalServiceServer) ValidateRetailerTerminal(context.Context, *ValidateRetailerTerminalRequest) (*ValidateRetailerTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRetailerTerminal not implemented")
}
func (UnimplementedTerminalServiceServer) mustEmbedUnimplementedTerminalServiceServer() {}
func (UnimplementedTerminalServiceServer) testEmbeddedByValue()                         {}

// UnsafeTerminalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerminalServiceServer will
// result in compilation errors.
type UnsafeTerminalServiceServer interface {
	mustEmbedUnimplementedTerminalServiceServer()
}

func RegisterTerminalServiceServer(s grpc.ServiceRegistrar, srv TerminalServiceServer) {
	// If the following call pancis, it indicates UnimplementedTerminalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TerminalService_ServiceDesc, srv)
}

func _TerminalService_RegisterTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).RegisterTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_RegisterTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).RegisterTerminal(ctx, req.(*RegisterTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_GetTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).GetTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_GetTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).GetTerminal(ctx, req.(*GetTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_UpdateTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).UpdateTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_UpdateTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).UpdateTerminal(ctx, req.(*UpdateTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_ListTerminals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTerminalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).ListTerminals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_ListTerminals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).ListTerminals(ctx, req.(*ListTerminalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_DeleteTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).DeleteTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_DeleteTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).DeleteTerminal(ctx, req.(*DeleteTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_AssignTerminalToRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).AssignTerminalToRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_AssignTerminalToRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).AssignTerminalToRetailer(ctx, req.(*AssignTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_UnassignTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).UnassignTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_UnassignTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).UnassignTerminal(ctx, req.(*UnassignTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_GetTerminalByRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerminalByRetailerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).GetTerminalByRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_GetTerminalByRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).GetTerminalByRetailer(ctx, req.(*GetTerminalByRetailerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_UpdateTerminalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTerminalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).UpdateTerminalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_UpdateTerminalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).UpdateTerminalStatus(ctx, req.(*UpdateTerminalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_UpdateTerminalHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTerminalHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).UpdateTerminalHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_UpdateTerminalHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).UpdateTerminalHealth(ctx, req.(*UpdateTerminalHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_GetTerminalHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerminalHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).GetTerminalHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_GetTerminalHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).GetTerminalHealth(ctx, req.(*GetTerminalHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_UpdateTerminalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTerminalConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).UpdateTerminalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_UpdateTerminalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).UpdateTerminalConfig(ctx, req.(*UpdateTerminalConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_GetTerminalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerminalConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).GetTerminalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_GetTerminalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).GetTerminalConfig(ctx, req.(*GetTerminalConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalService_ValidateRetailerTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRetailerTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalServiceServer).ValidateRetailerTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalService_ValidateRetailerTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalServiceServer).ValidateRetailerTerminal(ctx, req.(*ValidateRetailerTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TerminalService_ServiceDesc is the grpc.ServiceDesc for TerminalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerminalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terminal.v1.TerminalService",
	HandlerType: (*TerminalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTerminal",
			Handler:    _TerminalService_RegisterTerminal_Handler,
		},
		{
			MethodName: "GetTerminal",
			Handler:    _TerminalService_GetTerminal_Handler,
		},
		{
			MethodName: "UpdateTerminal",
			Handler:    _TerminalService_UpdateTerminal_Handler,
		},
		{
			MethodName: "ListTerminals",
			Handler:    _TerminalService_ListTerminals_Handler,
		},
		{
			MethodName: "DeleteTerminal",
			Handler:    _TerminalService_DeleteTerminal_Handler,
		},
		{
			MethodName: "AssignTerminalToRetailer",
			Handler:    _TerminalService_AssignTerminalToRetailer_Handler,
		},
		{
			MethodName: "UnassignTerminal",
			Handler:    _TerminalService_UnassignTerminal_Handler,
		},
		{
			MethodName: "GetTerminalByRetailer",
			Handler:    _TerminalService_GetTerminalByRetailer_Handler,
		},
		{
			MethodName: "UpdateTerminalStatus",
			Handler:    _TerminalService_UpdateTerminalStatus_Handler,
		},
		{
			MethodName: "UpdateTerminalHealth",
			Handler:    _TerminalService_UpdateTerminalHealth_Handler,
		},
		{
			MethodName: "GetTerminalHealth",
			Handler:    _TerminalService_GetTerminalHealth_Handler,
		},
		{
			MethodName: "UpdateTerminalConfig",
			Handler:    _TerminalService_UpdateTerminalConfig_Handler,
		},
		{
			MethodName: "GetTerminalConfig",
			Handler:    _TerminalService_GetTerminalConfig_Handler,
		},
		{
			MethodName: "ValidateRetailerTerminal",
			Handler:    _TerminalService_ValidateRetailerTerminal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/terminal/v1/terminal.proto",
}
