// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/agent/auth/v1/agent_auth.proto

package agentauthv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentAuthService_Login_FullMethodName                   = "/agent.auth.v1.AgentAuthService/Login"
	AgentAuthService_Logout_FullMethodName                  = "/agent.auth.v1.AgentAuthService/Logout"
	AgentAuthService_RefreshToken_FullMethodName            = "/agent.auth.v1.AgentAuthService/RefreshToken"
	AgentAuthService_ChangePassword_FullMethodName          = "/agent.auth.v1.AgentAuthService/ChangePassword"
	AgentAuthService_ChangeRetailerPIN_FullMethodName       = "/agent.auth.v1.AgentAuthService/ChangeRetailerPIN"
	AgentAuthService_CreateAgentAuth_FullMethodName         = "/agent.auth.v1.AgentAuthService/CreateAgentAuth"
	AgentAuthService_CreateRetailerAuth_FullMethodName      = "/agent.auth.v1.AgentAuthService/CreateRetailerAuth"
	AgentAuthService_AuthenticateRetailer_FullMethodName    = "/agent.auth.v1.AgentAuthService/AuthenticateRetailer"
	AgentAuthService_RegisterDevice_FullMethodName          = "/agent.auth.v1.AgentAuthService/RegisterDevice"
	AgentAuthService_UpdateDevice_FullMethodName            = "/agent.auth.v1.AgentAuthService/UpdateDevice"
	AgentAuthService_GetDevice_FullMethodName               = "/agent.auth.v1.AgentAuthService/GetDevice"
	AgentAuthService_ListAgentDevices_FullMethodName        = "/agent.auth.v1.AgentAuthService/ListAgentDevices"
	AgentAuthService_ActivateDevice_FullMethodName          = "/agent.auth.v1.AgentAuthService/ActivateDevice"
	AgentAuthService_DeactivateDevice_FullMethodName        = "/agent.auth.v1.AgentAuthService/DeactivateDevice"
	AgentAuthService_GenerateOfflineToken_FullMethodName    = "/agent.auth.v1.AgentAuthService/GenerateOfflineToken"
	AgentAuthService_ValidateOfflineToken_FullMethodName    = "/agent.auth.v1.AgentAuthService/ValidateOfflineToken"
	AgentAuthService_RevokeOfflineToken_FullMethodName      = "/agent.auth.v1.AgentAuthService/RevokeOfflineToken"
	AgentAuthService_ValidateToken_FullMethodName           = "/agent.auth.v1.AgentAuthService/ValidateToken"
	AgentAuthService_GetAgentPermissions_FullMethodName     = "/agent.auth.v1.AgentAuthService/GetAgentPermissions"
	AgentAuthService_InvalidateAgentSessions_FullMethodName = "/agent.auth.v1.AgentAuthService/InvalidateAgentSessions"
	AgentAuthService_ListAgentSessions_FullMethodName       = "/agent.auth.v1.AgentAuthService/ListAgentSessions"
	AgentAuthService_AgentCurrentSession_FullMethodName     = "/agent.auth.v1.AgentAuthService/AgentCurrentSession"
	AgentAuthService_RetailerPOSLogin_FullMethodName        = "/agent.auth.v1.AgentAuthService/RetailerPOSLogin"
	AgentAuthService_RequestPasswordReset_FullMethodName    = "/agent.auth.v1.AgentAuthService/RequestPasswordReset"
	AgentAuthService_ValidateResetOTP_FullMethodName        = "/agent.auth.v1.AgentAuthService/ValidateResetOTP"
	AgentAuthService_ConfirmPasswordReset_FullMethodName    = "/agent.auth.v1.AgentAuthService/ConfirmPasswordReset"
	AgentAuthService_ResendPasswordResetOTP_FullMethodName  = "/agent.auth.v1.AgentAuthService/ResendPasswordResetOTP"
)

// AgentAuthServiceClient is the client API for AgentAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentAuthService provides authentication and authorization for agents
type AgentAuthServiceClient interface {
	// Authentication operations
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ChangeRetailerPIN(ctx context.Context, in *ChangeRetailerPINRequest, opts ...grpc.CallOption) (*ChangeRetailerPINResponse, error)
	// Agent auth credential management
	CreateAgentAuth(ctx context.Context, in *CreateAgentAuthRequest, opts ...grpc.CallOption) (*CreateAgentAuthResponse, error)
	// Retailer auth credential management
	CreateRetailerAuth(ctx context.Context, in *CreateRetailerAuthRequest, opts ...grpc.CallOption) (*CreateRetailerAuthResponse, error)
	AuthenticateRetailer(ctx context.Context, in *RetailerAuthRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Device authentication for mobile POS
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error)
	ListAgentDevices(ctx context.Context, in *ListAgentDevicesRequest, opts ...grpc.CallOption) (*ListAgentDevicesResponse, error)
	ActivateDevice(ctx context.Context, in *ActivateDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error)
	DeactivateDevice(ctx context.Context, in *DeactivateDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error)
	// Offline token management
	GenerateOfflineToken(ctx context.Context, in *GenerateOfflineTokenRequest, opts ...grpc.CallOption) (*OfflineTokenResponse, error)
	ValidateOfflineToken(ctx context.Context, in *ValidateOfflineTokenRequest, opts ...grpc.CallOption) (*ValidateOfflineTokenResponse, error)
	RevokeOfflineToken(ctx context.Context, in *RevokeOfflineTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Token validation for internal services
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	GetAgentPermissions(ctx context.Context, in *GetAgentPermissionsRequest, opts ...grpc.CallOption) (*GetAgentPermissionsResponse, error)
	// Session management
	InvalidateAgentSessions(ctx context.Context, in *InvalidateAgentSessionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAgentSessions(ctx context.Context, in *ListAgentSessionsRequest, opts ...grpc.CallOption) (*ListAgentSessionsResponse, error)
	AgentCurrentSession(ctx context.Context, in *ListAgentSessionsRequest, opts ...grpc.CallOption) (*AgentCurrentSessionResponse, error)
	// Retailer POS authentication
	RetailerPOSLogin(ctx context.Context, in *RetailerPOSLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Password reset operations
	RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*PasswordResetResponse, error)
	ValidateResetOTP(ctx context.Context, in *ValidateResetOTPRequest, opts ...grpc.CallOption) (*ValidateResetOTPResponse, error)
	ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*ConfirmPasswordResetResponse, error)
	ResendPasswordResetOTP(ctx context.Context, in *ResendPasswordResetOTPRequest, opts ...grpc.CallOption) (*ResendPasswordResetOTPResponse, error)
}

type agentAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentAuthServiceClient(cc grpc.ClientConnInterface) AgentAuthServiceClient {
	return &agentAuthServiceClient{cc}
}

func (c *agentAuthServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentAuthService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentAuthService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ChangeRetailerPIN(ctx context.Context, in *ChangeRetailerPINRequest, opts ...grpc.CallOption) (*ChangeRetailerPINResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeRetailerPINResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ChangeRetailerPIN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) CreateAgentAuth(ctx context.Context, in *CreateAgentAuthRequest, opts ...grpc.CallOption) (*CreateAgentAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentAuthResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_CreateAgentAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) CreateRetailerAuth(ctx context.Context, in *CreateRetailerAuthRequest, opts ...grpc.CallOption) (*CreateRetailerAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRetailerAuthResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_CreateRetailerAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) AuthenticateRetailer(ctx context.Context, in *RetailerAuthRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_AuthenticateRetailer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthDevice)
	err := c.cc.Invoke(ctx, AgentAuthService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthDevice)
	err := c.cc.Invoke(ctx, AgentAuthService_UpdateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthDevice)
	err := c.cc.Invoke(ctx, AgentAuthService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ListAgentDevices(ctx context.Context, in *ListAgentDevicesRequest, opts ...grpc.CallOption) (*ListAgentDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentDevicesResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ListAgentDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ActivateDevice(ctx context.Context, in *ActivateDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthDevice)
	err := c.cc.Invoke(ctx, AgentAuthService_ActivateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) DeactivateDevice(ctx context.Context, in *DeactivateDeviceRequest, opts ...grpc.CallOption) (*AuthDevice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthDevice)
	err := c.cc.Invoke(ctx, AgentAuthService_DeactivateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) GenerateOfflineToken(ctx context.Context, in *GenerateOfflineTokenRequest, opts ...grpc.CallOption) (*OfflineTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfflineTokenResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_GenerateOfflineToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ValidateOfflineToken(ctx context.Context, in *ValidateOfflineTokenRequest, opts ...grpc.CallOption) (*ValidateOfflineTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateOfflineTokenResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ValidateOfflineToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) RevokeOfflineToken(ctx context.Context, in *RevokeOfflineTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentAuthService_RevokeOfflineToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) GetAgentPermissions(ctx context.Context, in *GetAgentPermissionsRequest, opts ...grpc.CallOption) (*GetAgentPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentPermissionsResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_GetAgentPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) InvalidateAgentSessions(ctx context.Context, in *InvalidateAgentSessionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentAuthService_InvalidateAgentSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ListAgentSessions(ctx context.Context, in *ListAgentSessionsRequest, opts ...grpc.CallOption) (*ListAgentSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentSessionsResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ListAgentSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) AgentCurrentSession(ctx context.Context, in *ListAgentSessionsRequest, opts ...grpc.CallOption) (*AgentCurrentSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentCurrentSessionResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_AgentCurrentSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) RetailerPOSLogin(ctx context.Context, in *RetailerPOSLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_RetailerPOSLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) RequestPasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*PasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordResetResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_RequestPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ValidateResetOTP(ctx context.Context, in *ValidateResetOTPRequest, opts ...grpc.CallOption) (*ValidateResetOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResetOTPResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ValidateResetOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*ConfirmPasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPasswordResetResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ConfirmPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAuthServiceClient) ResendPasswordResetOTP(ctx context.Context, in *ResendPasswordResetOTPRequest, opts ...grpc.CallOption) (*ResendPasswordResetOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendPasswordResetOTPResponse)
	err := c.cc.Invoke(ctx, AgentAuthService_ResendPasswordResetOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentAuthServiceServer is the server API for AgentAuthService service.
// All implementations must embed UnimplementedAgentAuthServiceServer
// for forward compatibility.
//
// AgentAuthService provides authentication and authorization for agents
type AgentAuthServiceServer interface {
	// Authentication operations
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error)
	ChangeRetailerPIN(context.Context, *ChangeRetailerPINRequest) (*ChangeRetailerPINResponse, error)
	// Agent auth credential management
	CreateAgentAuth(context.Context, *CreateAgentAuthRequest) (*CreateAgentAuthResponse, error)
	// Retailer auth credential management
	CreateRetailerAuth(context.Context, *CreateRetailerAuthRequest) (*CreateRetailerAuthResponse, error)
	AuthenticateRetailer(context.Context, *RetailerAuthRequest) (*LoginResponse, error)
	// Device authentication for mobile POS
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*AuthDevice, error)
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*AuthDevice, error)
	GetDevice(context.Context, *GetDeviceRequest) (*AuthDevice, error)
	ListAgentDevices(context.Context, *ListAgentDevicesRequest) (*ListAgentDevicesResponse, error)
	ActivateDevice(context.Context, *ActivateDeviceRequest) (*AuthDevice, error)
	DeactivateDevice(context.Context, *DeactivateDeviceRequest) (*AuthDevice, error)
	// Offline token management
	GenerateOfflineToken(context.Context, *GenerateOfflineTokenRequest) (*OfflineTokenResponse, error)
	ValidateOfflineToken(context.Context, *ValidateOfflineTokenRequest) (*ValidateOfflineTokenResponse, error)
	RevokeOfflineToken(context.Context, *RevokeOfflineTokenRequest) (*emptypb.Empty, error)
	// Token validation for internal services
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	GetAgentPermissions(context.Context, *GetAgentPermissionsRequest) (*GetAgentPermissionsResponse, error)
	// Session management
	InvalidateAgentSessions(context.Context, *InvalidateAgentSessionsRequest) (*emptypb.Empty, error)
	ListAgentSessions(context.Context, *ListAgentSessionsRequest) (*ListAgentSessionsResponse, error)
	AgentCurrentSession(context.Context, *ListAgentSessionsRequest) (*AgentCurrentSessionResponse, error)
	// Retailer POS authentication
	RetailerPOSLogin(context.Context, *RetailerPOSLoginRequest) (*LoginResponse, error)
	// Password reset operations
	RequestPasswordReset(context.Context, *PasswordResetRequest) (*PasswordResetResponse, error)
	ValidateResetOTP(context.Context, *ValidateResetOTPRequest) (*ValidateResetOTPResponse, error)
	ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*ConfirmPasswordResetResponse, error)
	ResendPasswordResetOTP(context.Context, *ResendPasswordResetOTPRequest) (*ResendPasswordResetOTPResponse, error)
	mustEmbedUnimplementedAgentAuthServiceServer()
}

// UnimplementedAgentAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentAuthServiceServer struct{}

func (UnimplementedAgentAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAgentAuthServiceServer) Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAgentAuthServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAgentAuthServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAgentAuthServiceServer) ChangeRetailerPIN(context.Context, *ChangeRetailerPINRequest) (*ChangeRetailerPINResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeRetailerPIN not implemented")
}
func (UnimplementedAgentAuthServiceServer) CreateAgentAuth(context.Context, *CreateAgentAuthRequest) (*CreateAgentAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgentAuth not implemented")
}
func (UnimplementedAgentAuthServiceServer) CreateRetailerAuth(context.Context, *CreateRetailerAuthRequest) (*CreateRetailerAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRetailerAuth not implemented")
}
func (UnimplementedAgentAuthServiceServer) AuthenticateRetailer(context.Context, *RetailerAuthRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateRetailer not implemented")
}
func (UnimplementedAgentAuthServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*AuthDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedAgentAuthServiceServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*AuthDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedAgentAuthServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*AuthDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedAgentAuthServiceServer) ListAgentDevices(context.Context, *ListAgentDevicesRequest) (*ListAgentDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentDevices not implemented")
}
func (UnimplementedAgentAuthServiceServer) ActivateDevice(context.Context, *ActivateDeviceRequest) (*AuthDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateDevice not implemented")
}
func (UnimplementedAgentAuthServiceServer) DeactivateDevice(context.Context, *DeactivateDeviceRequest) (*AuthDevice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateDevice not implemented")
}
func (UnimplementedAgentAuthServiceServer) GenerateOfflineToken(context.Context, *GenerateOfflineTokenRequest) (*OfflineTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateOfflineToken not implemented")
}
func (UnimplementedAgentAuthServiceServer) ValidateOfflineToken(context.Context, *ValidateOfflineTokenRequest) (*ValidateOfflineTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateOfflineToken not implemented")
}
func (UnimplementedAgentAuthServiceServer) RevokeOfflineToken(context.Context, *RevokeOfflineTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeOfflineToken not implemented")
}
func (UnimplementedAgentAuthServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAgentAuthServiceServer) GetAgentPermissions(context.Context, *GetAgentPermissionsRequest) (*GetAgentPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentPermissions not implemented")
}
func (UnimplementedAgentAuthServiceServer) InvalidateAgentSessions(context.Context, *InvalidateAgentSessionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateAgentSessions not implemented")
}
func (UnimplementedAgentAuthServiceServer) ListAgentSessions(context.Context, *ListAgentSessionsRequest) (*ListAgentSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentSessions not implemented")
}
func (UnimplementedAgentAuthServiceServer) AgentCurrentSession(context.Context, *ListAgentSessionsRequest) (*AgentCurrentSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentCurrentSession not implemented")
}
func (UnimplementedAgentAuthServiceServer) RetailerPOSLogin(context.Context, *RetailerPOSLoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetailerPOSLogin not implemented")
}
func (UnimplementedAgentAuthServiceServer) RequestPasswordReset(context.Context, *PasswordResetRequest) (*PasswordResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPasswordReset not implemented")
}
func (UnimplementedAgentAuthServiceServer) ValidateResetOTP(context.Context, *ValidateResetOTPRequest) (*ValidateResetOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateResetOTP not implemented")
}
func (UnimplementedAgentAuthServiceServer) ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*ConfirmPasswordResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPasswordReset not implemented")
}
func (UnimplementedAgentAuthServiceServer) ResendPasswordResetOTP(context.Context, *ResendPasswordResetOTPRequest) (*ResendPasswordResetOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendPasswordResetOTP not implemented")
}
func (UnimplementedAgentAuthServiceServer) mustEmbedUnimplementedAgentAuthServiceServer() {}
func (UnimplementedAgentAuthServiceServer) testEmbeddedByValue()                          {}

// UnsafeAgentAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentAuthServiceServer will
// result in compilation errors.
type UnsafeAgentAuthServiceServer interface {
	mustEmbedUnimplementedAgentAuthServiceServer()
}

func RegisterAgentAuthServiceServer(s grpc.ServiceRegistrar, srv AgentAuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentAuthService_ServiceDesc, srv)
}

func _AgentAuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ChangeRetailerPIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeRetailerPINRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ChangeRetailerPIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ChangeRetailerPIN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ChangeRetailerPIN(ctx, req.(*ChangeRetailerPINRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_CreateAgentAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).CreateAgentAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_CreateAgentAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).CreateAgentAuth(ctx, req.(*CreateAgentAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_CreateRetailerAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRetailerAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).CreateRetailerAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_CreateRetailerAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).CreateRetailerAuth(ctx, req.(*CreateRetailerAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_AuthenticateRetailer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetailerAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).AuthenticateRetailer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_AuthenticateRetailer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).AuthenticateRetailer(ctx, req.(*RetailerAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_UpdateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ListAgentDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ListAgentDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ListAgentDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ListAgentDevices(ctx, req.(*ListAgentDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ActivateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ActivateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ActivateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ActivateDevice(ctx, req.(*ActivateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_DeactivateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).DeactivateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_DeactivateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).DeactivateDevice(ctx, req.(*DeactivateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_GenerateOfflineToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateOfflineTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).GenerateOfflineToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_GenerateOfflineToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).GenerateOfflineToken(ctx, req.(*GenerateOfflineTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ValidateOfflineToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateOfflineTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ValidateOfflineToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ValidateOfflineToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ValidateOfflineToken(ctx, req.(*ValidateOfflineTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_RevokeOfflineToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeOfflineTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).RevokeOfflineToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_RevokeOfflineToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).RevokeOfflineToken(ctx, req.(*RevokeOfflineTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_GetAgentPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).GetAgentPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_GetAgentPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).GetAgentPermissions(ctx, req.(*GetAgentPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_InvalidateAgentSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateAgentSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).InvalidateAgentSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_InvalidateAgentSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).InvalidateAgentSessions(ctx, req.(*InvalidateAgentSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ListAgentSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ListAgentSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ListAgentSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ListAgentSessions(ctx, req.(*ListAgentSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_AgentCurrentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).AgentCurrentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_AgentCurrentSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).AgentCurrentSession(ctx, req.(*ListAgentSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_RetailerPOSLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetailerPOSLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).RetailerPOSLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_RetailerPOSLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).RetailerPOSLogin(ctx, req.(*RetailerPOSLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_RequestPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).RequestPasswordReset(ctx, req.(*PasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ValidateResetOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateResetOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ValidateResetOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ValidateResetOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ValidateResetOTP(ctx, req.(*ValidateResetOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ConfirmPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ConfirmPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ConfirmPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ConfirmPasswordReset(ctx, req.(*ConfirmPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAuthService_ResendPasswordResetOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendPasswordResetOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAuthServiceServer).ResendPasswordResetOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAuthService_ResendPasswordResetOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAuthServiceServer).ResendPasswordResetOTP(ctx, req.(*ResendPasswordResetOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentAuthService_ServiceDesc is the grpc.ServiceDesc for AgentAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.auth.v1.AgentAuthService",
	HandlerType: (*AgentAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AgentAuthService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AgentAuthService_Logout_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AgentAuthService_RefreshToken_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AgentAuthService_ChangePassword_Handler,
		},
		{
			MethodName: "ChangeRetailerPIN",
			Handler:    _AgentAuthService_ChangeRetailerPIN_Handler,
		},
		{
			MethodName: "CreateAgentAuth",
			Handler:    _AgentAuthService_CreateAgentAuth_Handler,
		},
		{
			MethodName: "CreateRetailerAuth",
			Handler:    _AgentAuthService_CreateRetailerAuth_Handler,
		},
		{
			MethodName: "AuthenticateRetailer",
			Handler:    _AgentAuthService_AuthenticateRetailer_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _AgentAuthService_RegisterDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _AgentAuthService_UpdateDevice_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _AgentAuthService_GetDevice_Handler,
		},
		{
			MethodName: "ListAgentDevices",
			Handler:    _AgentAuthService_ListAgentDevices_Handler,
		},
		{
			MethodName: "ActivateDevice",
			Handler:    _AgentAuthService_ActivateDevice_Handler,
		},
		{
			MethodName: "DeactivateDevice",
			Handler:    _AgentAuthService_DeactivateDevice_Handler,
		},
		{
			MethodName: "GenerateOfflineToken",
			Handler:    _AgentAuthService_GenerateOfflineToken_Handler,
		},
		{
			MethodName: "ValidateOfflineToken",
			Handler:    _AgentAuthService_ValidateOfflineToken_Handler,
		},
		{
			MethodName: "RevokeOfflineToken",
			Handler:    _AgentAuthService_RevokeOfflineToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AgentAuthService_ValidateToken_Handler,
		},
		{
			MethodName: "GetAgentPermissions",
			Handler:    _AgentAuthService_GetAgentPermissions_Handler,
		},
		{
			MethodName: "InvalidateAgentSessions",
			Handler:    _AgentAuthService_InvalidateAgentSessions_Handler,
		},
		{
			MethodName: "ListAgentSessions",
			Handler:    _AgentAuthService_ListAgentSessions_Handler,
		},
		{
			MethodName: "AgentCurrentSession",
			Handler:    _AgentAuthService_AgentCurrentSession_Handler,
		},
		{
			MethodName: "RetailerPOSLogin",
			Handler:    _AgentAuthService_RetailerPOSLogin_Handler,
		},
		{
			MethodName: "RequestPasswordReset",
			Handler:    _AgentAuthService_RequestPasswordReset_Handler,
		},
		{
			MethodName: "ValidateResetOTP",
			Handler:    _AgentAuthService_ValidateResetOTP_Handler,
		},
		{
			MethodName: "ConfirmPasswordReset",
			Handler:    _AgentAuthService_ConfirmPasswordReset_Handler,
		},
		{
			MethodName: "ResendPasswordResetOTP",
			Handler:    _AgentAuthService_ResendPasswordResetOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agent/auth/v1/agent_auth.proto",
}
