apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database credentials
  DATABASE_PASSWORD: "Player2025Secure"
  DATABASE_URL: "postgresql://player:Player2025Secure@postgres-player.external-services.svc.cluster.local:5432/player_service?sslmode=disable"

  # Redis password
  REDIS_PASSWORD: "Player2025RedisPassword"
  REDIS_URL: "redis://:Player2025RedisPassword@redis-player.external-services.svc.cluster.local:6390/0"

  # JWT configuration
  SECURITY_JWT_SECRET: "randlotteryltd-jwt-secret-h8f9x2w1v7q5k3m9n6b4c8d2e5f7g0j1"
