// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority_Level int32

const (
	Priority_LEVEL_UNSPECIFIED Priority_Level = 0
	Priority_LEVEL_LOW         Priority_Level = 1
	Priority_LEVEL_NORMAL      Priority_Level = 2
	Priority_LEVEL_HIGH        Priority_Level = 3
	Priority_LEVEL_CRITICAL    Priority_Level = 4
)

// Enum value maps for Priority_Level.
var (
	Priority_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_LOW",
		2: "LEVEL_NORMAL",
		3: "LEVEL_HIGH",
		4: "LEVEL_CRITICAL",
	}
	Priority_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_LOW":         1,
		"LEVEL_NORMAL":      2,
		"LEVEL_HIGH":        3,
		"LEVEL_CRITICAL":    4,
	}
)

func (x Priority_Level) Enum() *Priority_Level {
	p := new(Priority_Level)
	*p = x
	return p
}

func (x Priority_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (Priority_Level) Type() protoreflect.EnumType {
	return &file_proto_notification_v1_notification_proto_enumTypes[0]
}

func (x Priority_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority_Level.Descriptor instead.
func (Priority_Level) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{18, 0}
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendPushNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	To             string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"` // device token
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Data           map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // additional data
	Priority       *Priority              `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	TemplateId     string                 `protobuf:"bytes,7,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ScheduledFor   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	Variables      map[string]string      `protobuf:"bytes,9,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendPushNotificationRequest) Reset() {
	*x = SendPushNotificationRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPushNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPushNotificationRequest) ProtoMessage() {}

func (x *SendPushNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPushNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendPushNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendPushNotificationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendPushNotificationRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendPushNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendPushNotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendPushNotificationRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendPushNotificationRequest) GetPriority() *Priority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *SendPushNotificationRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendPushNotificationRequest) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

func (x *SendPushNotificationRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type SendBulkSMSRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       []*SendSMSRequest      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	TemplateId     string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ScheduledFor   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendBulkSMSRequest) Reset() {
	*x = SendBulkSMSRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkSMSRequest) ProtoMessage() {}

func (x *SendBulkSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkSMSRequest.ProtoReflect.Descriptor instead.
func (*SendBulkSMSRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendBulkSMSRequest) GetRequests() []*SendSMSRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *SendBulkSMSRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendBulkSMSRequest) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

func (x *SendBulkSMSRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendBulkSMSRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SendBulkPushRequest struct {
	state          protoimpl.MessageState         `protogen:"open.v1"`
	Requests       []*SendPushNotificationRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	TemplateId     string                         `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Title          string                         `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                         `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ScheduledFor   *timestamppb.Timestamp         `protobuf:"bytes,5,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	IdempotencyKey string                         `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendBulkPushRequest) Reset() {
	*x = SendBulkPushRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkPushRequest) ProtoMessage() {}

func (x *SendBulkPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkPushRequest.ProtoReflect.Descriptor instead.
func (*SendBulkPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SendBulkPushRequest) GetRequests() []*SendPushNotificationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *SendBulkPushRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendBulkPushRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendBulkPushRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendBulkPushRequest) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

func (x *SendBulkPushRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SendBulkEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       []*SendEmailRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	TemplateId     string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Subject        string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	ScheduledFor   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendBulkEmailRequest) Reset() {
	*x = SendBulkEmailRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailRequest) ProtoMessage() {}

func (x *SendBulkEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailRequest.ProtoReflect.Descriptor instead.
func (*SendBulkEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SendBulkEmailRequest) GetRequests() []*SendEmailRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *SendBulkEmailRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendBulkEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendBulkEmailRequest) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

func (x *SendBulkEmailRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SendBulkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*SendResponse        `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkResponse) Reset() {
	*x = SendBulkResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkResponse) ProtoMessage() {}

func (x *SendBulkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkResponse.ProtoReflect.Descriptor instead.
func (*SendBulkResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *SendBulkResponse) GetResponses() []*SendResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type NotificationStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                 // "pending", "sent", "failed"
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // if failed
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`                   // timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationStatus) Reset() {
	*x = NotificationStatus{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationStatus) ProtoMessage() {}

func (x *NotificationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationStatus.ProtoReflect.Descriptor instead.
func (*NotificationStatus) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationStatus) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *NotificationStatus) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // e.g., "SERVING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RetryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetryRequest) Reset() {
	*x = RetryRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRequest) ProtoMessage() {}

func (x *RetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRequest.ProtoReflect.Descriptor instead.
func (*RetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{10}
}

func (x *RetryRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // e.g., "status:failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{11}
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{12}
}

func (x *ListResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`       // "email", "sms", "push"
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`           // email address or phone number or device token
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"` // for email
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                 // "pending", "sent", "failed"
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // if failed
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // timestamp
	Priority      *Priority              `protobuf:"bytes,10,opt,name=priority,proto3" json:"priority,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"` // timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{13}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Notification) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Notification) GetPriority() *Priority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *Notification) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type SendEmailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	To             string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Cc             []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc            []string               `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject        string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateId     string                 `protobuf:"bytes,6,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Variables      map[string]string      `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HtmlContent    string                 `protobuf:"bytes,8,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"` // if not using template
	TextContent    string                 `protobuf:"bytes,9,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"` // if not using template
	Attachments    []*Attachment          `protobuf:"bytes,10,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Priority       *Priority              `protobuf:"bytes,11,opt,name=priority,proto3" json:"priority,omitempty"`
	ScheduledFor   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{14}
}

func (x *SendEmailRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailRequest) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendEmailRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SendEmailRequest) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

func (x *SendEmailRequest) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *SendEmailRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendEmailRequest) GetPriority() *Priority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *SendEmailRequest) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // base64 encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{15}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendSMSRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	To             string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TemplateId     string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Variables      map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"` // if not using template
	Priority       *Priority              `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	ScheduledFor   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=scheduled_for,json=scheduledFor,proto3" json:"scheduled_for,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendSMSRequest) Reset() {
	*x = SendSMSRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSRequest) ProtoMessage() {}

func (x *SendSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSRequest.ProtoReflect.Descriptor instead.
func (*SendSMSRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{16}
}

func (x *SendSMSRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SendSMSRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendSMSRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendSMSRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SendSMSRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendSMSRequest) GetPriority() *Priority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *SendSMSRequest) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledFor
	}
	return nil
}

type SendResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	IsDuplicate    bool                   `protobuf:"varint,4,opt,name=is_duplicate,json=isDuplicate,proto3" json:"is_duplicate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{17}
}

func (x *SendResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendResponse) GetIsDuplicate() bool {
	if x != nil {
		return x.IsDuplicate
	}
	return false
}

type Priority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         Priority_Level         `protobuf:"varint,1,opt,name=level,proto3,enum=notification.v1.Priority_Level" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Priority) Reset() {
	*x = Priority{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Priority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Priority) ProtoMessage() {}

func (x *Priority) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Priority.ProtoReflect.Descriptor instead.
func (*Priority) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{18}
}

func (x *Priority) GetLevel() Priority_Level {
	if x != nil {
		return x.Level
	}
	return Priority_LEVEL_UNSPECIFIED
}

// Device token registration messages
type RegisterDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetailerId    string                 `protobuf:"bytes,1,opt,name=retailer_id,json=retailerId,proto3" json:"retailer_id,omitempty"` // 8-digit retailer code (from JWT context)
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // Android device ID
	FcmToken      string                 `protobuf:"bytes,3,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`       // Firebase Cloud Messaging token
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`                       // 'android' or 'ios'
	AppVersion    string                 `protobuf:"bytes,5,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"` // App version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceTokenRequest) Reset() {
	*x = RegisterDeviceTokenRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceTokenRequest) ProtoMessage() {}

func (x *RegisterDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterDeviceTokenRequest) GetRetailerId() string {
	if x != nil {
		return x.RetailerId
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type RegisterDeviceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TokenId       string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"` // UUID of registered token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceTokenResponse) Reset() {
	*x = RegisterDeviceTokenResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceTokenResponse) ProtoMessage() {}

func (x *RegisterDeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterDeviceTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterDeviceTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterDeviceTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

// Retailer notification messages
type GetRetailerNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetailerId    string                 `protobuf:"bytes,1,opt,name=retailer_id,json=retailerId,proto3" json:"retailer_id,omitempty"` // 8-digit retailer code (from JWT context)
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UnreadOnly    bool                   `protobuf:"varint,4,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"` // Filter for unread only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRetailerNotificationsRequest) Reset() {
	*x = GetRetailerNotificationsRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetailerNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailerNotificationsRequest) ProtoMessage() {}

func (x *GetRetailerNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailerNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetRetailerNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{21}
}

func (x *GetRetailerNotificationsRequest) GetRetailerId() string {
	if x != nil {
		return x.RetailerId
	}
	return ""
}

func (x *GetRetailerNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRetailerNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRetailerNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

type GetRetailerNotificationsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Notifications []*RetailerNotification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	TotalCount    int32                   `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                   `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	UnreadCount   int32                   `protobuf:"varint,6,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRetailerNotificationsResponse) Reset() {
	*x = GetRetailerNotificationsResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRetailerNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRetailerNotificationsResponse) ProtoMessage() {}

func (x *GetRetailerNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRetailerNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetRetailerNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{22}
}

func (x *GetRetailerNotificationsResponse) GetNotifications() []*RetailerNotification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetRetailerNotificationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetRetailerNotificationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRetailerNotificationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRetailerNotificationsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetRetailerNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type RetailerNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 'stake', 'winning', 'commission', 'low_balance', 'general'
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                   // Amount in pesewas (GHS * 100), 0 if not applicable
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // Related transaction ID
	IsRead        bool                   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetailerNotification) Reset() {
	*x = RetailerNotification{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetailerNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetailerNotification) ProtoMessage() {}

func (x *RetailerNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetailerNotification.ProtoReflect.Descriptor instead.
func (*RetailerNotification) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{23}
}

func (x *RetailerNotification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RetailerNotification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RetailerNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RetailerNotification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RetailerNotification) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RetailerNotification) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RetailerNotification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *RetailerNotification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MarkNotificationAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RetailerId     string                 `protobuf:"bytes,1,opt,name=retailer_id,json=retailerId,proto3" json:"retailer_id,omitempty"`             // 8-digit retailer code (from JWT context)
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"` // UUID of notification
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationAsReadRequest) Reset() {
	*x = MarkNotificationAsReadRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationAsReadRequest) ProtoMessage() {}

func (x *MarkNotificationAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{24}
}

func (x *MarkNotificationAsReadRequest) GetRetailerId() string {
	if x != nil {
		return x.RetailerId
	}
	return ""
}

func (x *MarkNotificationAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type MarkAllNotificationsAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetailerId    string                 `protobuf:"bytes,1,opt,name=retailer_id,json=retailerId,proto3" json:"retailer_id,omitempty"` // 8-digit retailer code (from JWT context)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllNotificationsAsReadRequest) Reset() {
	*x = MarkAllNotificationsAsReadRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllNotificationsAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllNotificationsAsReadRequest) ProtoMessage() {}

func (x *MarkAllNotificationsAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllNotificationsAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllNotificationsAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{25}
}

func (x *MarkAllNotificationsAsReadRequest) GetRetailerId() string {
	if x != nil {
		return x.RetailerId
	}
	return ""
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetailerId    string                 `protobuf:"bytes,1,opt,name=retailer_id,json=retailerId,proto3" json:"retailer_id,omitempty"` // 8-digit retailer code (from JWT context)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{26}
}

func (x *GetUnreadCountRequest) GetRetailerId() string {
	if x != nil {
		return x.RetailerId
	}
	return ""
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int32                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_proto_notification_v1_notification_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_notification_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_notification_proto_rawDescGZIP(), []int{27}
}

func (x *GetUnreadCountResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_proto_notification_v1_notification_proto protoreflect.FileDescriptor

const file_proto_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"(proto/notification/v1/notification.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fEmptyRequest\"+\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb7\x04\n" +
	"\x1bSendPushNotificationRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12J\n" +
	"\x04data\x18\x05 \x03(\v26.notification.v1.SendPushNotificationRequest.DataEntryR\x04data\x125\n" +
	"\bpriority\x18\x06 \x01(\v2\x19.notification.v1.PriorityR\bpriority\x12\x1f\n" +
	"\vtemplate_id\x18\a \x01(\tR\n" +
	"templateId\x12?\n" +
	"\rscheduled_for\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x12Y\n" +
	"\tvariables\x18\t \x03(\v2;.notification.v1.SendPushNotificationRequest.VariablesEntryR\tvariables\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x12SendBulkSMSRequest\x12;\n" +
	"\brequests\x18\x01 \x03(\v2\x1f.notification.v1.SendSMSRequestR\brequests\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12?\n" +
	"\rscheduled_for\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\x94\x02\n" +
	"\x13SendBulkPushRequest\x12H\n" +
	"\brequests\x18\x01 \x03(\v2,.notification.v1.SendPushNotificationRequestR\brequests\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12?\n" +
	"\rscheduled_for\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\xfa\x01\n" +
	"\x14SendBulkEmailRequest\x12=\n" +
	"\brequests\x18\x01 \x03(\v2!.notification.v1.SendEmailRequestR\brequests\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12?\n" +
	"\rscheduled_for\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"O\n" +
	"\x10SendBulkResponse\x12;\n" +
	"\tresponses\x18\x01 \x03(\v2\x1d.notification.v1.SendResponseR\tresponses\";\n" +
	"\x10GetStatusRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\xaf\x01\n" +
	"\x12NotificationStatus\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x123\n" +
	"\asent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"7\n" +
	"\fRetryRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"V\n" +
	"\vListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xa5\x01\n" +
	"\fListResponse\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.notification.v1.NotificationR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x95\x03\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x125\n" +
	"\bpriority\x18\n" +
	" \x01(\v2\x19.notification.v1.PriorityR\bpriority\x123\n" +
	"\asent_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xb3\x04\n" +
	"\x10SendEmailRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x04 \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x1f\n" +
	"\vtemplate_id\x18\x06 \x01(\tR\n" +
	"templateId\x12N\n" +
	"\tvariables\x18\a \x03(\v20.notification.v1.SendEmailRequest.VariablesEntryR\tvariables\x12!\n" +
	"\fhtml_content\x18\b \x01(\tR\vhtmlContent\x12!\n" +
	"\ftext_content\x18\t \x01(\tR\vtextContent\x12=\n" +
	"\vattachments\x18\n" +
	" \x03(\v2\x1b.notification.v1.AttachmentR\vattachments\x125\n" +
	"\bpriority\x18\v \x01(\v2\x19.notification.v1.PriorityR\bpriority\x12?\n" +
	"\rscheduled_for\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x88\x03\n" +
	"\x0eSendSMSRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12L\n" +
	"\tvariables\x18\x04 \x03(\v2..notification.v1.SendSMSRequest.VariablesEntryR\tvariables\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x125\n" +
	"\bpriority\x18\x06 \x01(\v2\x19.notification.v1.PriorityR\bpriority\x12?\n" +
	"\rscheduled_for\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\fSendResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fis_duplicate\x18\x04 \x01(\bR\visDuplicate\"\xa6\x01\n" +
	"\bPriority\x125\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1f.notification.v1.Priority.LevelR\x05level\"c\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tLEVEL_LOW\x10\x01\x12\x10\n" +
	"\fLEVEL_NORMAL\x10\x02\x12\x0e\n" +
	"\n" +
	"LEVEL_HIGH\x10\x03\x12\x12\n" +
	"\x0eLEVEL_CRITICAL\x10\x04\"\xb4\x01\n" +
	"\x1aRegisterDeviceTokenRequest\x12\x1f\n" +
	"\vretailer_id\x18\x01 \x01(\tR\n" +
	"retailerId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tfcm_token\x18\x03 \x01(\tR\bfcmToken\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1f\n" +
	"\vapp_version\x18\x05 \x01(\tR\n" +
	"appVersion\"l\n" +
	"\x1bRegisterDeviceTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\"\x94\x01\n" +
	"\x1fGetRetailerNotificationsRequest\x12\x1f\n" +
	"\vretailer_id\x18\x01 \x01(\tR\n" +
	"retailerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vunread_only\x18\x04 \x01(\bR\n" +
	"unreadOnly\"\x85\x02\n" +
	" GetRetailerNotificationsResponse\x12K\n" +
	"\rnotifications\x18\x01 \x03(\v2%.notification.v1.RetailerNotificationR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\funread_count\x18\x06 \x01(\x05R\vunreadCount\"\xf7\x01\n" +
	"\x14RetailerNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x12\x17\n" +
	"\ais_read\x18\a \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"i\n" +
	"\x1dMarkNotificationAsReadRequest\x12\x1f\n" +
	"\vretailer_id\x18\x01 \x01(\tR\n" +
	"retailerId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"D\n" +
	"!MarkAllNotificationsAsReadRequest\x12\x1f\n" +
	"\vretailer_id\x18\x01 \x01(\tR\n" +
	"retailerId\"8\n" +
	"\x15GetUnreadCountRequest\x12\x1f\n" +
	"\vretailer_id\x18\x01 \x01(\tR\n" +
	"retailerId\";\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_count\x18\x01 \x01(\x05R\vunreadCount2\xb2\v\n" +
	"\x13NotificationService\x12R\n" +
	"\vHealthCheck\x12\x1d.notification.v1.EmptyRequest\x1a$.notification.v1.HealthCheckResponse\x12M\n" +
	"\tSendEmail\x12!.notification.v1.SendEmailRequest\x1a\x1d.notification.v1.SendResponse\x12I\n" +
	"\aSendSMS\x12\x1f.notification.v1.SendSMSRequest\x1a\x1d.notification.v1.SendResponse\x12X\n" +
	"\rSendBulkEmail\x12%.notification.v1.SendBulkEmailRequest\x1a .notification.v1.GenericResponse\x12T\n" +
	"\vSendBulkSMS\x12#.notification.v1.SendBulkSMSRequest\x1a .notification.v1.GenericResponse\x12V\n" +
	"\fSendBulkPush\x12$.notification.v1.SendBulkPushRequest\x1a .notification.v1.GenericResponse\x12i\n" +
	"\x1aSendMobilePushNotification\x12,.notification.v1.SendPushNotificationRequest\x1a\x1d.notification.v1.SendResponse\x12_\n" +
	"\x15GetNotificationStatus\x12!.notification.v1.GetStatusRequest\x1a#.notification.v1.NotificationStatus\x12P\n" +
	"\x11ListNotifications\x12\x1c.notification.v1.ListRequest\x1a\x1d.notification.v1.ListResponse\x12Q\n" +
	"\x11RetryNotification\x12\x1d.notification.v1.RetryRequest\x1a\x1d.notification.v1.SendResponse\x12p\n" +
	"\x13RegisterDeviceToken\x12+.notification.v1.RegisterDeviceTokenRequest\x1a,.notification.v1.RegisterDeviceTokenResponse\x12\x7f\n" +
	"\x18GetRetailerNotifications\x120.notification.v1.GetRetailerNotificationsRequest\x1a1.notification.v1.GetRetailerNotificationsResponse\x12j\n" +
	"\x16MarkNotificationAsRead\x12..notification.v1.MarkNotificationAsReadRequest\x1a .notification.v1.GenericResponse\x12r\n" +
	"\x1aMarkAllNotificationsAsRead\x122.notification.v1.MarkAllNotificationsAsReadRequest\x1a .notification.v1.GenericResponse\x12a\n" +
	"\x0eGetUnreadCount\x12&.notification.v1.GetUnreadCountRequest\x1a'.notification.v1.GetUnreadCountResponseBMZKgithub.com/randco/randco-microservices/proto/notification/v1;notificationv1b\x06proto3"

var (
	file_proto_notification_v1_notification_proto_rawDescOnce sync.Once
	file_proto_notification_v1_notification_proto_rawDescData []byte
)

func file_proto_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_v1_notification_proto_rawDesc), len(file_proto_notification_v1_notification_proto_rawDesc)))
	})
	return file_proto_notification_v1_notification_proto_rawDescData
}

var file_proto_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_notification_v1_notification_proto_goTypes = []any{
	(Priority_Level)(0),                       // 0: notification.v1.Priority.Level
	(*EmptyRequest)(nil),                      // 1: notification.v1.EmptyRequest
	(*GenericResponse)(nil),                   // 2: notification.v1.GenericResponse
	(*SendPushNotificationRequest)(nil),       // 3: notification.v1.SendPushNotificationRequest
	(*SendBulkSMSRequest)(nil),                // 4: notification.v1.SendBulkSMSRequest
	(*SendBulkPushRequest)(nil),               // 5: notification.v1.SendBulkPushRequest
	(*SendBulkEmailRequest)(nil),              // 6: notification.v1.SendBulkEmailRequest
	(*SendBulkResponse)(nil),                  // 7: notification.v1.SendBulkResponse
	(*GetStatusRequest)(nil),                  // 8: notification.v1.GetStatusRequest
	(*NotificationStatus)(nil),                // 9: notification.v1.NotificationStatus
	(*HealthCheckResponse)(nil),               // 10: notification.v1.HealthCheckResponse
	(*RetryRequest)(nil),                      // 11: notification.v1.RetryRequest
	(*ListRequest)(nil),                       // 12: notification.v1.ListRequest
	(*ListResponse)(nil),                      // 13: notification.v1.ListResponse
	(*Notification)(nil),                      // 14: notification.v1.Notification
	(*SendEmailRequest)(nil),                  // 15: notification.v1.SendEmailRequest
	(*Attachment)(nil),                        // 16: notification.v1.Attachment
	(*SendSMSRequest)(nil),                    // 17: notification.v1.SendSMSRequest
	(*SendResponse)(nil),                      // 18: notification.v1.SendResponse
	(*Priority)(nil),                          // 19: notification.v1.Priority
	(*RegisterDeviceTokenRequest)(nil),        // 20: notification.v1.RegisterDeviceTokenRequest
	(*RegisterDeviceTokenResponse)(nil),       // 21: notification.v1.RegisterDeviceTokenResponse
	(*GetRetailerNotificationsRequest)(nil),   // 22: notification.v1.GetRetailerNotificationsRequest
	(*GetRetailerNotificationsResponse)(nil),  // 23: notification.v1.GetRetailerNotificationsResponse
	(*RetailerNotification)(nil),              // 24: notification.v1.RetailerNotification
	(*MarkNotificationAsReadRequest)(nil),     // 25: notification.v1.MarkNotificationAsReadRequest
	(*MarkAllNotificationsAsReadRequest)(nil), // 26: notification.v1.MarkAllNotificationsAsReadRequest
	(*GetUnreadCountRequest)(nil),             // 27: notification.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),            // 28: notification.v1.GetUnreadCountResponse
	nil,                                       // 29: notification.v1.SendPushNotificationRequest.DataEntry
	nil,                                       // 30: notification.v1.SendPushNotificationRequest.VariablesEntry
	nil,                                       // 31: notification.v1.SendEmailRequest.VariablesEntry
	nil,                                       // 32: notification.v1.SendSMSRequest.VariablesEntry
	(*timestamppb.Timestamp)(nil),             // 33: google.protobuf.Timestamp
}
var file_proto_notification_v1_notification_proto_depIdxs = []int32{
	29, // 0: notification.v1.SendPushNotificationRequest.data:type_name -> notification.v1.SendPushNotificationRequest.DataEntry
	19, // 1: notification.v1.SendPushNotificationRequest.priority:type_name -> notification.v1.Priority
	33, // 2: notification.v1.SendPushNotificationRequest.scheduled_for:type_name -> google.protobuf.Timestamp
	30, // 3: notification.v1.SendPushNotificationRequest.variables:type_name -> notification.v1.SendPushNotificationRequest.VariablesEntry
	17, // 4: notification.v1.SendBulkSMSRequest.requests:type_name -> notification.v1.SendSMSRequest
	33, // 5: notification.v1.SendBulkSMSRequest.scheduled_for:type_name -> google.protobuf.Timestamp
	3,  // 6: notification.v1.SendBulkPushRequest.requests:type_name -> notification.v1.SendPushNotificationRequest
	33, // 7: notification.v1.SendBulkPushRequest.scheduled_for:type_name -> google.protobuf.Timestamp
	15, // 8: notification.v1.SendBulkEmailRequest.requests:type_name -> notification.v1.SendEmailRequest
	33, // 9: notification.v1.SendBulkEmailRequest.scheduled_for:type_name -> google.protobuf.Timestamp
	18, // 10: notification.v1.SendBulkResponse.responses:type_name -> notification.v1.SendResponse
	33, // 11: notification.v1.NotificationStatus.sent_at:type_name -> google.protobuf.Timestamp
	14, // 12: notification.v1.ListResponse.notifications:type_name -> notification.v1.Notification
	33, // 13: notification.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	33, // 14: notification.v1.Notification.updated_at:type_name -> google.protobuf.Timestamp
	19, // 15: notification.v1.Notification.priority:type_name -> notification.v1.Priority
	33, // 16: notification.v1.Notification.sent_at:type_name -> google.protobuf.Timestamp
	31, // 17: notification.v1.SendEmailRequest.variables:type_name -> notification.v1.SendEmailRequest.VariablesEntry
	16, // 18: notification.v1.SendEmailRequest.attachments:type_name -> notification.v1.Attachment
	19, // 19: notification.v1.SendEmailRequest.priority:type_name -> notification.v1.Priority
	33, // 20: notification.v1.SendEmailRequest.scheduled_for:type_name -> google.protobuf.Timestamp
	32, // 21: notification.v1.SendSMSRequest.variables:type_name -> notification.v1.SendSMSRequest.VariablesEntry
	19, // 22: notification.v1.SendSMSRequest.priority:type_name -> notification.v1.Priority
	33, // 23: notification.v1.SendSMSRequest.scheduled_for:type_name -> google.protobuf.Timestamp
	0,  // 24: notification.v1.Priority.level:type_name -> notification.v1.Priority.Level
	24, // 25: notification.v1.GetRetailerNotificationsResponse.notifications:type_name -> notification.v1.RetailerNotification
	33, // 26: notification.v1.RetailerNotification.created_at:type_name -> google.protobuf.Timestamp
	1,  // 27: notification.v1.NotificationService.HealthCheck:input_type -> notification.v1.EmptyRequest
	15, // 28: notification.v1.NotificationService.SendEmail:input_type -> notification.v1.SendEmailRequest
	17, // 29: notification.v1.NotificationService.SendSMS:input_type -> notification.v1.SendSMSRequest
	6,  // 30: notification.v1.NotificationService.SendBulkEmail:input_type -> notification.v1.SendBulkEmailRequest
	4,  // 31: notification.v1.NotificationService.SendBulkSMS:input_type -> notification.v1.SendBulkSMSRequest
	5,  // 32: notification.v1.NotificationService.SendBulkPush:input_type -> notification.v1.SendBulkPushRequest
	3,  // 33: notification.v1.NotificationService.SendMobilePushNotification:input_type -> notification.v1.SendPushNotificationRequest
	8,  // 34: notification.v1.NotificationService.GetNotificationStatus:input_type -> notification.v1.GetStatusRequest
	12, // 35: notification.v1.NotificationService.ListNotifications:input_type -> notification.v1.ListRequest
	11, // 36: notification.v1.NotificationService.RetryNotification:input_type -> notification.v1.RetryRequest
	20, // 37: notification.v1.NotificationService.RegisterDeviceToken:input_type -> notification.v1.RegisterDeviceTokenRequest
	22, // 38: notification.v1.NotificationService.GetRetailerNotifications:input_type -> notification.v1.GetRetailerNotificationsRequest
	25, // 39: notification.v1.NotificationService.MarkNotificationAsRead:input_type -> notification.v1.MarkNotificationAsReadRequest
	26, // 40: notification.v1.NotificationService.MarkAllNotificationsAsRead:input_type -> notification.v1.MarkAllNotificationsAsReadRequest
	27, // 41: notification.v1.NotificationService.GetUnreadCount:input_type -> notification.v1.GetUnreadCountRequest
	10, // 42: notification.v1.NotificationService.HealthCheck:output_type -> notification.v1.HealthCheckResponse
	18, // 43: notification.v1.NotificationService.SendEmail:output_type -> notification.v1.SendResponse
	18, // 44: notification.v1.NotificationService.SendSMS:output_type -> notification.v1.SendResponse
	2,  // 45: notification.v1.NotificationService.SendBulkEmail:output_type -> notification.v1.GenericResponse
	2,  // 46: notification.v1.NotificationService.SendBulkSMS:output_type -> notification.v1.GenericResponse
	2,  // 47: notification.v1.NotificationService.SendBulkPush:output_type -> notification.v1.GenericResponse
	18, // 48: notification.v1.NotificationService.SendMobilePushNotification:output_type -> notification.v1.SendResponse
	9,  // 49: notification.v1.NotificationService.GetNotificationStatus:output_type -> notification.v1.NotificationStatus
	13, // 50: notification.v1.NotificationService.ListNotifications:output_type -> notification.v1.ListResponse
	18, // 51: notification.v1.NotificationService.RetryNotification:output_type -> notification.v1.SendResponse
	21, // 52: notification.v1.NotificationService.RegisterDeviceToken:output_type -> notification.v1.RegisterDeviceTokenResponse
	23, // 53: notification.v1.NotificationService.GetRetailerNotifications:output_type -> notification.v1.GetRetailerNotificationsResponse
	2,  // 54: notification.v1.NotificationService.MarkNotificationAsRead:output_type -> notification.v1.GenericResponse
	2,  // 55: notification.v1.NotificationService.MarkAllNotificationsAsRead:output_type -> notification.v1.GenericResponse
	28, // 56: notification.v1.NotificationService.GetUnreadCount:output_type -> notification.v1.GetUnreadCountResponse
	42, // [42:57] is the sub-list for method output_type
	27, // [27:42] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_notification_v1_notification_proto_init() }
func file_proto_notification_v1_notification_proto_init() {
	if File_proto_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_v1_notification_proto_rawDesc), len(file_proto_notification_v1_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_proto_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_proto_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_v1_notification_proto = out.File
	file_proto_notification_v1_notification_proto_goTypes = nil
	file_proto_notification_v1_notification_proto_depIdxs = nil
}
