-- +goose Up
-- +goose StatementBegin

-- Update agent_code field to align with agent-management service format
-- Agent codes are numeric only (e.g., 1001, 1002, etc.) as generated by agent-management
COMMENT ON COLUMN agents_auth.agent_code IS '4-digit unique number (e.g., 1001), expandable to 5+ digits';

-- Add check constraint to ensure agent codes are numeric
ALTER TABLE agents_auth DROP CONSTRAINT IF EXISTS agents_auth_agent_code_check;
ALTER TABLE agents_auth ADD CONSTRAINT agents_auth_agent_code_check CHECK (agent_code ~ '^\d+$');

-- Update retailer_code field comment to match agent-management format
COMMENT ON COLUMN retailers_auth.retailer_code IS '8-digit code: Agent-managed=[4-digit agent code][4-digit sequence], Independent=0000[4-digit sequence]';

-- Add check constraint to ensure retailer codes are 8 digits
ALTER TABLE retailers_auth DROP CONSTRAINT IF EXISTS retailers_auth_retailer_code_check;
ALTER TABLE retailers_auth ADD CONSTRAINT retailers_auth_retailer_code_check CHECK (retailer_code ~ '^\d{8}$');

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Remove the new constraints
ALTER TABLE agents_auth DROP CONSTRAINT IF EXISTS agents_auth_agent_code_check;
ALTER TABLE retailers_auth DROP CONSTRAINT IF EXISTS retailers_auth_retailer_code_check;

-- Remove comments
COMMENT ON COLUMN agents_auth.agent_code IS NULL;
COMMENT ON COLUMN retailers_auth.retailer_code IS NULL;

-- +goose StatementEnd
